package org.komea.event.model.beans;

import java.util.Date;

public abstract class AbstractEvent {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column kom_evt_storage.provider
	 *
	 * @mbggenerated Sun Nov 16 12:30:58 CET 2014
	 */
	protected String	provider;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column kom_evt_storage.eventKey
	 *
	 * @mbggenerated Sun Nov 16 12:30:58 CET 2014
	 */
	protected String	eventType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column kom_evt_storage.date
	 *
	 * @mbggenerated Sun Nov 16 12:30:58 CET 2014
	 */
	protected Date	 date;

	public AbstractEvent() {
		super();
		this.date = new Date();
	}

	public AbstractEvent(final String _provider, final String _eventType, final Date _newDate) {
		this.provider = _provider;
		this.eventType = _eventType;
		this.date = _newDate;
	}

	public final Date getDate() {
		return this.date;
	}

	public final String getEventType() {
		return this.eventType;
	}

	public final String getProvider() {
		return this.provider;
	}

	public final void setDate(final Date date) {
		this.date = date;
	}

	public void setEventType(final String _eventType) {
		this.eventType = _eventType;
	}

	public final void setProvider(final String provider) {
		this.provider = provider;
	}

	@Override
	public String toString() {
		return "BasicEvent [provider=" + this.provider + ", eventType=" + this.eventType + ", date=" + this.date + "]";
	}

}