/**
 *
 */
package org.komea.product.backend.service.generic;

import java.io.Serializable;
import java.util.List;
import org.komea.product.database.api.IHasKey;

/**
 * This service defines a generic.
 *
 * @author sleroy
 */
public interface IGenericService<TEntity extends IHasKey, PK extends Serializable, TCriteria> {

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table kom_tag
     *
     * @mbggenerated Fri Feb 14 12:56:55 CET 2014
     */
    int countByCriteria(TCriteria example);

    /**
     * Delete the entity
     *
     * @param _entity the entity to delete
     */
    void delete(TEntity _entity);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table kom_tag
     *
     * @mbggenerated Fri Feb 14 12:56:55 CET 2014
     */
    int deleteByCriteria(TCriteria example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table kom_tag
     *
     * @mbggenerated Fri Feb 14 12:56:55 CET 2014
     */
    int deleteByPrimaryKey(PK id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table kom_tag
     *
     * @mbggenerated Fri Feb 14 12:56:55 CET 2014
     */
    int insert(TEntity record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table kom_tag
     *
     * @mbggenerated Fri Feb 14 12:56:55 CET 2014
     */
    int insertSelective(TEntity record);

    /**
     * Save or update.
     *
     * @param _tEntity the entity.
     */
    void saveOrUpdate(TEntity _tEntity);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table kom_tag
     *
     * @mbggenerated Fri Feb 14 12:56:55 CET 2014
     */
    List<TEntity> selectByCriteria(TCriteria example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table kom_tag
     *
     * @mbggenerated Fri Feb 14 12:56:55 CET 2014
     */
    List<TEntity> selectByCriteriaWithRowbounds(TCriteria example, int offset, int limit);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table kom_tag
     *
     * @mbggenerated Fri Feb 14 12:56:55 CET 2014
     */
    TEntity selectByPrimaryKey(PK id);

    /**
     * get list of entities from their ids
     *
     * @param _ids ids of the entities
     * @return list of entities
     */
    List<TEntity> selectByPrimaryKeyList(final List<PK> _ids);

    /**
     * get all entities
     *
     * @return list of all entities
     */
    List<TEntity> selectAll();

    TEntity selectByKey(String key);

    List<TEntity> selectByKeys(List<String> keys);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table kom_tag
     *
     * @mbggenerated Fri Feb 14 12:56:55 CET 2014
     */
    int updateByCriteria(TEntity record, TCriteria example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table kom_tag
     *
     * @mbggenerated Fri Feb 14 12:56:55 CET 2014
     */
    int updateByCriteriaSelective(TEntity record, TCriteria example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table kom_tag
     *
     * @mbggenerated Fri Feb 14 12:56:55 CET 2014
     */
    int updateByPrimaryKey(TEntity record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table kom_tag
     *
     * @mbggenerated Fri Feb 14 12:56:55 CET 2014
     */
    int updateByPrimaryKeySelective(TEntity record);

}
