package org.komea.product.eventory.database.model;

import java.io.Serializable;
import java.util.Date;

import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

import org.komea.product.eventory.dao.api.IEventSerializable;

import com.orientechnologies.orient.core.record.impl.ODocument;

public class BasicEvent implements IEventSerializable, Serializable {

	/**
	 * Constant to describe the date field
	 */
	public static final String FIELD_DATE = "date";
	/**
	 * Constant to describe the event key field
	 */
	public static final String FIELD_EVENTKEY = "eventKey";

	/**
	 * Constant to describe the provider field
	 */
	public static final String FIELD_PROVIDER = "provider";

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column kom_evt_storage.provider
	 *
	 * @mbggenerated Sun Nov 16 12:30:58 CET 2014
	 */
	@NotNull
	@Size(min = 0, max = 255)
	private String provider;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column kom_evt_storage.eventKey
	 *
	 * @mbggenerated Sun Nov 16 12:30:58 CET 2014
	 */
	@NotNull
	@Size(min = 0, max = 255)
	private String eventKey;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column kom_evt_storage.date
	 *
	 * @mbggenerated Sun Nov 16 12:30:58 CET 2014
	 */
	@NotNull
	private Date date;

	public final Date getDate() {
		return this.date;
	}

	@Override
	public final String getEventKey() {
		return this.eventKey;
	}

	public final String getProvider() {
		return this.provider;
	}

	@Override
	public void serialize(final ODocument _document) {
		_document.field(FIELD_EVENTKEY, this.eventKey);
		_document.field(FIELD_PROVIDER, this.provider);
		_document.field(FIELD_DATE, this.date);

	}

	public final void setDate(final Date date) {
		this.date = date;
	}

	public final void setEventKey(final String eventKey) {
		this.eventKey = eventKey;
	}

	public final void setProvider(final String provider) {
		this.provider = provider;
	}

	@Override
	public final String toString() {
		return "EventStorage [provider=" + this.provider + ", eventKey="
				+ this.eventKey + ", date=" + this.date + "]";
	}

}