package org.komea.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.komea.model.KomEvt;
import org.komea.model.KomEvtExample;

public interface KomEvtMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kom_evt
     *
     * @mbggenerated Wed Jan 08 15:34:10 CET 2014
     */
    int countByExample(KomEvtExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kom_evt
     *
     * @mbggenerated Wed Jan 08 15:34:10 CET 2014
     */
    int deleteByExample(KomEvtExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kom_evt
     *
     * @mbggenerated Wed Jan 08 15:34:10 CET 2014
     */
    int deleteByPrimaryKey(Integer idEventType);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kom_evt
     *
     * @mbggenerated Wed Jan 08 15:34:10 CET 2014
     */
    int insert(KomEvt record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kom_evt
     *
     * @mbggenerated Wed Jan 08 15:34:10 CET 2014
     */
    int insertSelective(KomEvt record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kom_evt
     *
     * @mbggenerated Wed Jan 08 15:34:10 CET 2014
     */
    List<KomEvt> selectByExampleWithBLOBs(KomEvtExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kom_evt
     *
     * @mbggenerated Wed Jan 08 15:34:10 CET 2014
     */
    List<KomEvt> selectByExample(KomEvtExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kom_evt
     *
     * @mbggenerated Wed Jan 08 15:34:10 CET 2014
     */
    KomEvt selectByPrimaryKey(Integer idEventType);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kom_evt
     *
     * @mbggenerated Wed Jan 08 15:34:10 CET 2014
     */
    int updateByExampleSelective(@Param("record") KomEvt record, @Param("example") KomEvtExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kom_evt
     *
     * @mbggenerated Wed Jan 08 15:34:10 CET 2014
     */
    int updateByExampleWithBLOBs(@Param("record") KomEvt record, @Param("example") KomEvtExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kom_evt
     *
     * @mbggenerated Wed Jan 08 15:34:10 CET 2014
     */
    int updateByExample(@Param("record") KomEvt record, @Param("example") KomEvtExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kom_evt
     *
     * @mbggenerated Wed Jan 08 15:34:10 CET 2014
     */
    int updateByPrimaryKeySelective(KomEvt record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kom_evt
     *
     * @mbggenerated Wed Jan 08 15:34:10 CET 2014
     */
    int updateByPrimaryKeyWithBLOBs(KomEvt record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kom_evt
     *
     * @mbggenerated Wed Jan 08 15:34:10 CET 2014
     */
    int updateByPrimaryKey(KomEvt record);
}