package org.komea.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.komea.model.KomHasProjKpiaExample;
import org.komea.model.KomHasProjKpiaKey;

public interface KomHasProjKpiaMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kom_has_proj_kpia
     *
     * @mbggenerated Wed Jan 08 15:34:10 CET 2014
     */
    int countByExample(KomHasProjKpiaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kom_has_proj_kpia
     *
     * @mbggenerated Wed Jan 08 15:34:10 CET 2014
     */
    int deleteByExample(KomHasProjKpiaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kom_has_proj_kpia
     *
     * @mbggenerated Wed Jan 08 15:34:10 CET 2014
     */
    int deleteByPrimaryKey(KomHasProjKpiaKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kom_has_proj_kpia
     *
     * @mbggenerated Wed Jan 08 15:34:10 CET 2014
     */
    int insert(KomHasProjKpiaKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kom_has_proj_kpia
     *
     * @mbggenerated Wed Jan 08 15:34:10 CET 2014
     */
    int insertSelective(KomHasProjKpiaKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kom_has_proj_kpia
     *
     * @mbggenerated Wed Jan 08 15:34:10 CET 2014
     */
    List<KomHasProjKpiaKey> selectByExample(KomHasProjKpiaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kom_has_proj_kpia
     *
     * @mbggenerated Wed Jan 08 15:34:10 CET 2014
     */
    int updateByExampleSelective(@Param("record") KomHasProjKpiaKey record, @Param("example") KomHasProjKpiaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kom_has_proj_kpia
     *
     * @mbggenerated Wed Jan 08 15:34:10 CET 2014
     */
    int updateByExample(@Param("record") KomHasProjKpiaKey record, @Param("example") KomHasProjKpiaExample example);
}