package org.komea.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.komea.model.KomKpi;
import org.komea.model.KomKpiExample;
import org.komea.model.KomKpiWithBLOBs;

public interface KomKpiMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kom_kpi
     *
     * @mbggenerated Wed Jan 08 15:34:10 CET 2014
     */
    int countByExample(KomKpiExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kom_kpi
     *
     * @mbggenerated Wed Jan 08 15:34:10 CET 2014
     */
    int deleteByExample(KomKpiExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kom_kpi
     *
     * @mbggenerated Wed Jan 08 15:34:10 CET 2014
     */
    int deleteByPrimaryKey(Integer idKpi);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kom_kpi
     *
     * @mbggenerated Wed Jan 08 15:34:10 CET 2014
     */
    int insert(KomKpiWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kom_kpi
     *
     * @mbggenerated Wed Jan 08 15:34:10 CET 2014
     */
    int insertSelective(KomKpiWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kom_kpi
     *
     * @mbggenerated Wed Jan 08 15:34:10 CET 2014
     */
    List<KomKpiWithBLOBs> selectByExampleWithBLOBs(KomKpiExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kom_kpi
     *
     * @mbggenerated Wed Jan 08 15:34:10 CET 2014
     */
    List<KomKpi> selectByExample(KomKpiExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kom_kpi
     *
     * @mbggenerated Wed Jan 08 15:34:10 CET 2014
     */
    KomKpiWithBLOBs selectByPrimaryKey(Integer idKpi);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kom_kpi
     *
     * @mbggenerated Wed Jan 08 15:34:10 CET 2014
     */
    int updateByExampleSelective(@Param("record") KomKpiWithBLOBs record, @Param("example") KomKpiExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kom_kpi
     *
     * @mbggenerated Wed Jan 08 15:34:10 CET 2014
     */
    int updateByExampleWithBLOBs(@Param("record") KomKpiWithBLOBs record, @Param("example") KomKpiExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kom_kpi
     *
     * @mbggenerated Wed Jan 08 15:34:10 CET 2014
     */
    int updateByExample(@Param("record") KomKpi record, @Param("example") KomKpiExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kom_kpi
     *
     * @mbggenerated Wed Jan 08 15:34:10 CET 2014
     */
    int updateByPrimaryKeySelective(KomKpiWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kom_kpi
     *
     * @mbggenerated Wed Jan 08 15:34:10 CET 2014
     */
    int updateByPrimaryKeyWithBLOBs(KomKpiWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kom_kpi
     *
     * @mbggenerated Wed Jan 08 15:34:10 CET 2014
     */
    int updateByPrimaryKey(KomKpi record);
}