package org.komea.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.komea.model.KomLink;
import org.komea.model.KomLinkExample;

public interface KomLinkMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kom_link
     *
     * @mbggenerated Wed Jan 08 15:34:10 CET 2014
     */
    int countByExample(KomLinkExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kom_link
     *
     * @mbggenerated Wed Jan 08 15:34:10 CET 2014
     */
    int deleteByExample(KomLinkExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kom_link
     *
     * @mbggenerated Wed Jan 08 15:34:10 CET 2014
     */
    int deleteByPrimaryKey(Integer idLink);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kom_link
     *
     * @mbggenerated Wed Jan 08 15:34:10 CET 2014
     */
    int insert(KomLink record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kom_link
     *
     * @mbggenerated Wed Jan 08 15:34:10 CET 2014
     */
    int insertSelective(KomLink record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kom_link
     *
     * @mbggenerated Wed Jan 08 15:34:10 CET 2014
     */
    List<KomLink> selectByExample(KomLinkExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kom_link
     *
     * @mbggenerated Wed Jan 08 15:34:10 CET 2014
     */
    KomLink selectByPrimaryKey(Integer idLink);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kom_link
     *
     * @mbggenerated Wed Jan 08 15:34:10 CET 2014
     */
    int updateByExampleSelective(@Param("record") KomLink record, @Param("example") KomLinkExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kom_link
     *
     * @mbggenerated Wed Jan 08 15:34:10 CET 2014
     */
    int updateByExample(@Param("record") KomLink record, @Param("example") KomLinkExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kom_link
     *
     * @mbggenerated Wed Jan 08 15:34:10 CET 2014
     */
    int updateByPrimaryKeySelective(KomLink record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kom_link
     *
     * @mbggenerated Wed Jan 08 15:34:10 CET 2014
     */
    int updateByPrimaryKey(KomLink record);
}