package org.komea.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.komea.model.KomPero;
import org.komea.model.KomPeroExample;

public interface KomPeroMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kom_pero
     *
     * @mbggenerated Wed Jan 08 15:34:10 CET 2014
     */
    int countByExample(KomPeroExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kom_pero
     *
     * @mbggenerated Wed Jan 08 15:34:10 CET 2014
     */
    int deleteByExample(KomPeroExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kom_pero
     *
     * @mbggenerated Wed Jan 08 15:34:10 CET 2014
     */
    int deleteByPrimaryKey(Integer idPersonRole);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kom_pero
     *
     * @mbggenerated Wed Jan 08 15:34:10 CET 2014
     */
    int insert(KomPero record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kom_pero
     *
     * @mbggenerated Wed Jan 08 15:34:10 CET 2014
     */
    int insertSelective(KomPero record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kom_pero
     *
     * @mbggenerated Wed Jan 08 15:34:10 CET 2014
     */
    List<KomPero> selectByExample(KomPeroExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kom_pero
     *
     * @mbggenerated Wed Jan 08 15:34:10 CET 2014
     */
    KomPero selectByPrimaryKey(Integer idPersonRole);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kom_pero
     *
     * @mbggenerated Wed Jan 08 15:34:10 CET 2014
     */
    int updateByExampleSelective(@Param("record") KomPero record, @Param("example") KomPeroExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kom_pero
     *
     * @mbggenerated Wed Jan 08 15:34:10 CET 2014
     */
    int updateByExample(@Param("record") KomPero record, @Param("example") KomPeroExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kom_pero
     *
     * @mbggenerated Wed Jan 08 15:34:10 CET 2014
     */
    int updateByPrimaryKeySelective(KomPero record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kom_pero
     *
     * @mbggenerated Wed Jan 08 15:34:10 CET 2014
     */
    int updateByPrimaryKey(KomPero record);
}