CREATE TABLE IF NOT EXISTS `#table#` (
`id` bigint(20) NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `date` DATETIME NOT NULL,
  `provider` VARCHAR(128) NOT NULL,
  `data` BLOB NOT NULL,
  INDEX (`date`)
);

