package org.komea.product.database.enums;

public enum ExtendedEntityType {

    PROJECT, PERSON, TEAM, DEPARTMENT,
    TEAM_PROJECTS_SUM, TEAM_PROJECTS_AVERAGE,
    TEAM_PERSONS_SUM, TEAM_PERSONS_AVERAGE,
    DEPARTMENT_PROJECTS_SUM, DEPARTMENT_PROJECTS_AVERAGE,
    DEPARTMENT_PERSONS_SUM, DEPARTMENT_PERSONS_AVERAGE
}
