package org.komea.model;

public class KomKpiWithBLOBs extends KomKpi {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kom_kpi.description
     *
     * @mbggenerated Wed Jan 08 15:34:10 CET 2014
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kom_kpi.esperRequest
     *
     * @mbggenerated Wed Jan 08 15:34:10 CET 2014
     */
    private String esperRequest;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kom_kpi.description
     *
     * @return the value of kom_kpi.description
     *
     * @mbggenerated Wed Jan 08 15:34:10 CET 2014
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kom_kpi.description
     *
     * @param description the value for kom_kpi.description
     *
     * @mbggenerated Wed Jan 08 15:34:10 CET 2014
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kom_kpi.esperRequest
     *
     * @return the value of kom_kpi.esperRequest
     *
     * @mbggenerated Wed Jan 08 15:34:10 CET 2014
     */
    public String getEsperRequest() {
        return esperRequest;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kom_kpi.esperRequest
     *
     * @param esperRequest the value for kom_kpi.esperRequest
     *
     * @mbggenerated Wed Jan 08 15:34:10 CET 2014
     */
    public void setEsperRequest(String esperRequest) {
        this.esperRequest = esperRequest == null ? null : esperRequest.trim();
    }
}