package org.komea.model;

public class KomPvd {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kom_pvd.idProvider
     *
     * @mbggenerated Wed Jan 08 15:34:10 CET 2014
     */
    private Integer idProvider;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kom_pvd.key
     *
     * @mbggenerated Wed Jan 08 15:34:10 CET 2014
     */
    private String key;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kom_pvd.name
     *
     * @mbggenerated Wed Jan 08 15:34:10 CET 2014
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kom_pvd.icon
     *
     * @mbggenerated Wed Jan 08 15:34:10 CET 2014
     */
    private String icon;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kom_pvd.url
     *
     * @mbggenerated Wed Jan 08 15:34:10 CET 2014
     */
    private String url;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kom_pvd.idProvider
     *
     * @return the value of kom_pvd.idProvider
     *
     * @mbggenerated Wed Jan 08 15:34:10 CET 2014
     */
    public Integer getIdProvider() {
        return idProvider;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kom_pvd.idProvider
     *
     * @param idProvider the value for kom_pvd.idProvider
     *
     * @mbggenerated Wed Jan 08 15:34:10 CET 2014
     */
    public void setIdProvider(Integer idProvider) {
        this.idProvider = idProvider;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kom_pvd.key
     *
     * @return the value of kom_pvd.key
     *
     * @mbggenerated Wed Jan 08 15:34:10 CET 2014
     */
    public String getKey() {
        return key;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kom_pvd.key
     *
     * @param key the value for kom_pvd.key
     *
     * @mbggenerated Wed Jan 08 15:34:10 CET 2014
     */
    public void setKey(String key) {
        this.key = key == null ? null : key.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kom_pvd.name
     *
     * @return the value of kom_pvd.name
     *
     * @mbggenerated Wed Jan 08 15:34:10 CET 2014
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kom_pvd.name
     *
     * @param name the value for kom_pvd.name
     *
     * @mbggenerated Wed Jan 08 15:34:10 CET 2014
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kom_pvd.icon
     *
     * @return the value of kom_pvd.icon
     *
     * @mbggenerated Wed Jan 08 15:34:10 CET 2014
     */
    public String getIcon() {
        return icon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kom_pvd.icon
     *
     * @param icon the value for kom_pvd.icon
     *
     * @mbggenerated Wed Jan 08 15:34:10 CET 2014
     */
    public void setIcon(String icon) {
        this.icon = icon == null ? null : icon.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kom_pvd.url
     *
     * @return the value of kom_pvd.url
     *
     * @mbggenerated Wed Jan 08 15:34:10 CET 2014
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kom_pvd.url
     *
     * @param url the value for kom_pvd.url
     *
     * @mbggenerated Wed Jan 08 15:34:10 CET 2014
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }
}