/*
* generated by Xtext
*/
package org.komea.events.dsl.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.komea.events.dsl.services.EventDslGrammarAccess;

public class EventDslParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private EventDslGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected org.komea.events.dsl.parser.antlr.internal.InternalEventDslParser createParser(XtextTokenStream stream) {
		return new org.komea.events.dsl.parser.antlr.internal.InternalEventDslParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "EventFactory";
	}
	
	public EventDslGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(EventDslGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
