package org.komea.product.database.model;

import java.io.Serializable;
import javax.validation.constraints.NotNull;
import org.komea.product.database.enums.EntityType;
import org.komea.product.database.enums.RetentionPeriod;

public class ActivityFilter implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kom_acfi.id
     *
     * @mbggenerated Thu Feb 20 01:05:41 CET 2014
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kom_acfi.entityType
     *
     * @mbggenerated Thu Feb 20 01:05:41 CET 2014
     */
    @NotNull
    private EntityType entityType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kom_acfi.idEntity
     *
     * @mbggenerated Thu Feb 20 01:05:41 CET 2014
     */
    private Integer idEntity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kom_acfi.infoRetention
     *
     * @mbggenerated Thu Feb 20 01:05:41 CET 2014
     */
    @NotNull
    private RetentionPeriod infoRetention;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kom_acfi.minorRetention
     *
     * @mbggenerated Thu Feb 20 01:05:41 CET 2014
     */
    @NotNull
    private RetentionPeriod minorRetention;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kom_acfi.majorRetention
     *
     * @mbggenerated Thu Feb 20 01:05:41 CET 2014
     */
    @NotNull
    private RetentionPeriod majorRetention;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kom_acfi.criticalRetention
     *
     * @mbggenerated Thu Feb 20 01:05:41 CET 2014
     */
    @NotNull
    private RetentionPeriod criticalRetention;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kom_acfi.blockerRetention
     *
     * @mbggenerated Thu Feb 20 01:05:41 CET 2014
     */
    @NotNull
    private RetentionPeriod blockerRetention;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table kom_acfi
     *
     * @mbggenerated Thu Feb 20 01:05:41 CET 2014
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kom_acfi
     *
     * @mbggenerated Thu Feb 20 01:05:41 CET 2014
     */
    public ActivityFilter(Integer id, EntityType entityType, Integer idEntity, RetentionPeriod infoRetention, RetentionPeriod minorRetention, RetentionPeriod majorRetention, RetentionPeriod criticalRetention, RetentionPeriod blockerRetention) {
        this.id = id;
        this.entityType = entityType;
        this.idEntity = idEntity;
        this.infoRetention = infoRetention;
        this.minorRetention = minorRetention;
        this.majorRetention = majorRetention;
        this.criticalRetention = criticalRetention;
        this.blockerRetention = blockerRetention;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kom_acfi
     *
     * @mbggenerated Thu Feb 20 01:05:41 CET 2014
     */
    public ActivityFilter() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kom_acfi.id
     *
     * @return the value of kom_acfi.id
     *
     * @mbggenerated Thu Feb 20 01:05:41 CET 2014
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kom_acfi.id
     *
     * @param id the value for kom_acfi.id
     *
     * @mbggenerated Thu Feb 20 01:05:41 CET 2014
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kom_acfi.entityType
     *
     * @return the value of kom_acfi.entityType
     *
     * @mbggenerated Thu Feb 20 01:05:41 CET 2014
     */
    public EntityType getEntityType() {
        return entityType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kom_acfi.entityType
     *
     * @param entityType the value for kom_acfi.entityType
     *
     * @mbggenerated Thu Feb 20 01:05:41 CET 2014
     */
    public void setEntityType(EntityType entityType) {
        this.entityType = entityType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kom_acfi.idEntity
     *
     * @return the value of kom_acfi.idEntity
     *
     * @mbggenerated Thu Feb 20 01:05:41 CET 2014
     */
    public Integer getIdEntity() {
        return idEntity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kom_acfi.idEntity
     *
     * @param idEntity the value for kom_acfi.idEntity
     *
     * @mbggenerated Thu Feb 20 01:05:41 CET 2014
     */
    public void setIdEntity(Integer idEntity) {
        this.idEntity = idEntity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kom_acfi.infoRetention
     *
     * @return the value of kom_acfi.infoRetention
     *
     * @mbggenerated Thu Feb 20 01:05:41 CET 2014
     */
    public RetentionPeriod getInfoRetention() {
        return infoRetention;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kom_acfi.infoRetention
     *
     * @param infoRetention the value for kom_acfi.infoRetention
     *
     * @mbggenerated Thu Feb 20 01:05:41 CET 2014
     */
    public void setInfoRetention(RetentionPeriod infoRetention) {
        this.infoRetention = infoRetention;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kom_acfi.minorRetention
     *
     * @return the value of kom_acfi.minorRetention
     *
     * @mbggenerated Thu Feb 20 01:05:41 CET 2014
     */
    public RetentionPeriod getMinorRetention() {
        return minorRetention;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kom_acfi.minorRetention
     *
     * @param minorRetention the value for kom_acfi.minorRetention
     *
     * @mbggenerated Thu Feb 20 01:05:41 CET 2014
     */
    public void setMinorRetention(RetentionPeriod minorRetention) {
        this.minorRetention = minorRetention;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kom_acfi.majorRetention
     *
     * @return the value of kom_acfi.majorRetention
     *
     * @mbggenerated Thu Feb 20 01:05:41 CET 2014
     */
    public RetentionPeriod getMajorRetention() {
        return majorRetention;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kom_acfi.majorRetention
     *
     * @param majorRetention the value for kom_acfi.majorRetention
     *
     * @mbggenerated Thu Feb 20 01:05:41 CET 2014
     */
    public void setMajorRetention(RetentionPeriod majorRetention) {
        this.majorRetention = majorRetention;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kom_acfi.criticalRetention
     *
     * @return the value of kom_acfi.criticalRetention
     *
     * @mbggenerated Thu Feb 20 01:05:41 CET 2014
     */
    public RetentionPeriod getCriticalRetention() {
        return criticalRetention;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kom_acfi.criticalRetention
     *
     * @param criticalRetention the value for kom_acfi.criticalRetention
     *
     * @mbggenerated Thu Feb 20 01:05:41 CET 2014
     */
    public void setCriticalRetention(RetentionPeriod criticalRetention) {
        this.criticalRetention = criticalRetention;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kom_acfi.blockerRetention
     *
     * @return the value of kom_acfi.blockerRetention
     *
     * @mbggenerated Thu Feb 20 01:05:41 CET 2014
     */
    public RetentionPeriod getBlockerRetention() {
        return blockerRetention;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kom_acfi.blockerRetention
     *
     * @param blockerRetention the value for kom_acfi.blockerRetention
     *
     * @mbggenerated Thu Feb 20 01:05:41 CET 2014
     */
    public void setBlockerRetention(RetentionPeriod blockerRetention) {
        this.blockerRetention = blockerRetention;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kom_acfi
     *
     * @mbggenerated Thu Feb 20 01:05:41 CET 2014
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", entityType=").append(entityType);
        sb.append(", idEntity=").append(idEntity);
        sb.append(", infoRetention=").append(infoRetention);
        sb.append(", minorRetention=").append(minorRetention);
        sb.append(", majorRetention=").append(majorRetention);
        sb.append(", criticalRetention=").append(criticalRetention);
        sb.append(", blockerRetention=").append(blockerRetention);
        sb.append("]");
        return sb.toString();
    }
}