package org.komea.product.database.model;

import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;
import org.komea.product.database.api.IHasKey;
import org.komea.product.database.api.IKeyVisitor;
import org.komea.product.database.enums.EntityType;
import org.komea.product.database.enums.ProviderType;
import org.komea.product.database.enums.Severity;

public class EventType implements IHasKey {

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database table kom_evt
     *
     * @mbggenerated Thu Feb 20 01:05:41 CET 2014
     */
    private static final long serialVersionUID = 1L;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column kom_evt.description
     *
     * @mbggenerated Thu Feb 20 01:05:41 CET 2014
     */
    @Size(min = 0, max = 2048)
    private String description;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column kom_evt.enabled
     *
     * @mbggenerated Thu Feb 20 01:05:41 CET 2014
     */
    @NotNull
    private Boolean enabled;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column kom_evt.entityType
     *
     * @mbggenerated Thu Feb 20 01:05:41 CET 2014
     */
    private EntityType entityType;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column kom_evt.eventKey
     *
     * @mbggenerated Thu Feb 20 01:05:41 CET 2014
     */
    @NotNull
    @Size(min = 0, max = 255)
    private String eventKey;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column kom_evt.id
     *
     * @mbggenerated Thu Feb 20 01:05:41 CET 2014
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column kom_evt.name
     *
     * @mbggenerated Thu Feb 20 01:05:41 CET 2014
     */
    @NotNull
    @Size(min = 0, max = 255)
    private String name;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column kom_evt.severity
     *
     * @mbggenerated Thu Feb 20 01:05:41 CET 2014
     */
    @NotNull
    private Severity severity;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column kom_evt.providerType
     *
     * @mbggenerated Thu Mar 06 10:32:30 CET 2014
     */
    @NotNull
    private ProviderType providerType;

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table kom_evt
     *
     * @mbggenerated Thu Feb 20 01:05:41 CET 2014
     */
    public EventType() {

        super();
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table kom_evt
     *
     * @mbggenerated Thu Feb 20 01:05:41 CET 2014
     */
    public EventType(
            final Integer id,
            final String eventKey,
            final String name,
            final Severity severity,
            final Boolean enabled,
            final String description,
            final EntityType entityType,
            final ProviderType providerType) {

        this.id = id;
        this.eventKey = eventKey;
        this.name = name;
        this.severity = severity;
        this.enabled = enabled;
        this.description = description;
        this.entityType = entityType;
        this.providerType = providerType;
    }

    /*
     * (non-Javadoc)
     * @see org.komea.product.database.api.IHasKey#accept(org.komea.product.database.api.IKeyVisitor)
     * @mbggenerated Wed Feb 19 11:03:52 CET 2014
     */
    @Override
    public void accept(final IKeyVisitor _visitor) {

        _visitor.visit(this);

    }

    /*
     * (non-Javadoc)
     * @see java.lang.Object#equals(java.lang.Object)
     */
    @Override
    public boolean equals(final Object obj) {

        if (this == obj) {
            return true;
        }
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final EventType other = (EventType) obj;
        if (id == null) {
            if (other.id != null) {
                return false;
            }
        } else if (!id.equals(other.id)) {
            return false;
        }
        return true;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column kom_evt.description
     *
     * @return the value of kom_evt.description
     * @mbggenerated Thu Feb 20 01:05:41 CET 2014
     */
    public String getDescription() {

        return description;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column kom_evt.enabled
     *
     * @return the value of kom_evt.enabled
     * @mbggenerated Thu Feb 20 01:05:41 CET 2014
     */
    public Boolean getEnabled() {

        return enabled;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column kom_evt.entityType
     *
     * @return the value of kom_evt.entityType
     * @mbggenerated Thu Feb 20 01:05:41 CET 2014
     */
    public EntityType getEntityType() {

        return entityType;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column kom_evt.eventKey
     *
     * @return the value of kom_evt.eventKey
     * @mbggenerated Thu Feb 20 01:05:41 CET 2014
     */
    public String getEventKey() {

        return eventKey;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column kom_evt.id
     *
     * @return the value of kom_evt.id
     * @mbggenerated Thu Feb 20 01:05:41 CET 2014
     */
    @Override
    public Integer getId() {

        return id;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column kom_evt.name
     *
     * @return the value of kom_evt.name
     * @mbggenerated Thu Feb 20 01:05:41 CET 2014
     */
    public String getName() {

        return name;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column kom_evt.severity
     *
     * @return the value of kom_evt.severity
     * @mbggenerated Thu Feb 20 01:05:41 CET 2014
     */
    public Severity getSeverity() {

        return severity;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column kom_evt.providerType
     *
     * @return the value of kom_evt.providerType
     * @mbggenerated Thu Mar 06 10:32:30 CET 2014
     */
    public ProviderType getProviderType() {

        return providerType;
    }

    /*
     * (non-Javadoc)
     * @see java.lang.Object#hashCode()
     */
    @Override
    public int hashCode() {

        final int prime = 31;
        int result = 1;
        result = prime * result + (id == null ? 0 : id.hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column kom_evt.description
     *
     * @param description the value for kom_evt.description
     * @mbggenerated Thu Feb 20 01:05:41 CET 2014
     */
    public void setDescription(final String description) {

        this.description = description;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column kom_evt.enabled
     *
     * @param enabled the value for kom_evt.enabled
     * @mbggenerated Thu Feb 20 01:05:41 CET 2014
     */
    public void setEnabled(final Boolean enabled) {

        this.enabled = enabled;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column kom_evt.entityType
     *
     * @param entityType the value for kom_evt.entityType
     * @mbggenerated Thu Feb 20 01:05:41 CET 2014
     */
    public void setEntityType(final EntityType entityType) {

        this.entityType = entityType;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column kom_evt.eventKey
     *
     * @param eventKey the value for kom_evt.eventKey
     * @mbggenerated Thu Feb 20 01:05:41 CET 2014
     */
    public void setEventKey(final String eventKey) {

        this.eventKey = eventKey;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column kom_evt.id
     *
     * @param id the value for kom_evt.id
     * @mbggenerated Thu Feb 20 01:05:41 CET 2014
     */
    public void setId(final Integer id) {

        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column kom_evt.name
     *
     * @param name the value for kom_evt.name
     * @mbggenerated Thu Feb 20 01:05:41 CET 2014
     */
    public void setName(final String name) {

        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column kom_evt.severity
     *
     * @param severity the value for kom_evt.severity
     * @mbggenerated Thu Feb 20 01:05:41 CET 2014
     */
    public void setSeverity(final Severity severity) {

        this.severity = severity;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column kom_evt.providerType
     *
     * @param providerType the value for kom_evt.providerType
     * @mbggenerated Thu Mar 06 10:32:30 CET 2014
     */
    public void setProviderType(final ProviderType providerType) {

        this.providerType = providerType;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table kom_evt
     *
     * @mbggenerated Thu Feb 20 01:05:41 CET 2014
     */
    @Override
    public String toString() {

        final StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", eventKey=").append(eventKey);
        sb.append(", name=").append(name);
        sb.append(", severity=").append(severity);
        sb.append(", enabled=").append(enabled);
        sb.append(", description=").append(description);
        sb.append(", entityType=").append(entityType);
        sb.append(", providerType=").append(providerType);
        sb.append("]");
        return sb.toString();
    }
}
