
package org.komea.product.database.model;



import java.io.Serializable;

import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

import org.komea.product.database.api.IEntity;
import org.komea.product.database.enums.EntityType;
import org.komea.product.database.enums.EvictionType;
import org.komea.product.database.enums.ValueDirection;
import org.komea.product.database.enums.ValueType;



public class Kpi implements Serializable
{
    
    
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kom_kpi.id
     * 
     * @mbggenerated Wed Feb 05 15:26:17 CET 2014
     */
    private Integer           id;
    
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kom_kpi.kpiKey
     * 
     * @mbggenerated Wed Feb 05 15:26:17 CET 2014
     */
    @NotNull
    @Size(min = 0, max = 255)
    private String            kpiKey;
    
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kom_kpi.name
     * 
     * @mbggenerated Wed Feb 05 15:26:17 CET 2014
     */
    @NotNull
    @Size(min = 0, max = 255)
    private String            name;
    
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kom_kpi.description
     * 
     * @mbggenerated Wed Feb 05 15:26:17 CET 2014
     */
    @NotNull
    @Size(min = 0, max = 2048)
    private String            description;
    
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kom_kpi.idProvider
     * 
     * @mbggenerated Wed Feb 05 15:26:17 CET 2014
     */
    private Integer           idProvider;
    
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kom_kpi.minValue
     * 
     * @mbggenerated Wed Feb 05 15:26:17 CET 2014
     */
    private Double            minValue;
    
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kom_kpi.maxValue
     * 
     * @mbggenerated Wed Feb 05 15:26:17 CET 2014
     */
    private Double            maxValue;
    
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kom_kpi.valueDirection
     * 
     * @mbggenerated Wed Feb 05 15:26:17 CET 2014
     */
    @NotNull
    private ValueDirection    valueDirection;
    
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kom_kpi.valueType
     * 
     * @mbggenerated Wed Feb 05 15:26:17 CET 2014
     */
    @NotNull
    private ValueType         valueType;
    
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kom_kpi.entityType
     * 
     * @mbggenerated Wed Feb 05 15:26:17 CET 2014
     */
    @NotNull
    private EntityType        entityType;
    
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kom_kpi.entityID
     * 
     * @mbggenerated Wed Feb 05 15:26:17 CET 2014
     */
    private Integer           entityID;
    
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kom_kpi.cronExpression
     * 
     * @mbggenerated Wed Feb 05 15:26:17 CET 2014
     */
    @Size(min = 0, max = 60)
    private String            cronExpression;
    
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kom_kpi.evictionRate
     * 
     * @mbggenerated Wed Feb 05 15:26:17 CET 2014
     */
    @NotNull
    private Integer           evictionRate;
    
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kom_kpi.evictionType
     * 
     * @mbggenerated Wed Feb 05 15:26:17 CET 2014
     */
    @NotNull
    private EvictionType      evictionType;
    
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kom_kpi.esperRequest
     * 
     * @mbggenerated Wed Feb 05 15:26:17 CET 2014
     */
    @NotNull
    @Size(min = 0, max = 16777215)
    private String            esperRequest;
    
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table kom_kpi
     * 
     * @mbggenerated Wed Feb 05 15:26:17 CET 2014
     */
    private static final long serialVersionUID = 1L;
    
    
    
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kom_kpi
     * 
     * @mbggenerated Wed Feb 05 15:26:17 CET 2014
     */
    public Kpi() {
    
    
        super();
    }
    
    
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kom_kpi
     * 
     * @mbggenerated Wed Feb 05 15:26:17 CET 2014
     */
    public Kpi(
            final Integer id,
            final String kpiKey,
            final String name,
            final String description,
            final Integer idProvider,
            final Double minValue,
            final Double maxValue,
            final ValueDirection valueDirection,
            final ValueType valueType,
            final EntityType entityType,
            final Integer entityID,
            final String cronExpression,
            final Integer evictionRate,
            final EvictionType evictionType) {
    
    
        this.id = id;
        this.kpiKey = kpiKey;
        this.name = name;
        this.description = description;
        this.idProvider = idProvider;
        this.minValue = minValue;
        this.maxValue = maxValue;
        this.valueDirection = valueDirection;
        this.valueType = valueType;
        this.entityType = entityType;
        this.entityID = entityID;
        this.cronExpression = cronExpression;
        this.evictionRate = evictionRate;
        this.evictionType = evictionType;
        esperRequest = null;
    }
    
    
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kom_kpi
     * 
     * @mbggenerated Wed Feb 05 15:26:17 CET 2014
     */
    public Kpi(
            final Integer id,
            final String kpiKey,
            final String name,
            final String description,
            final Integer idProvider,
            final Double minValue,
            final Double maxValue,
            final ValueDirection valueDirection,
            final ValueType valueType,
            final EntityType entityType,
            final Integer entityID,
            final String cronExpression,
            final Integer evictionRate,
            final EvictionType evictionType,
            final String esperRequest) {
    
    
        this.id = id;
        this.kpiKey = kpiKey;
        this.name = name;
        this.description = description;
        this.idProvider = idProvider;
        this.minValue = minValue;
        this.maxValue = maxValue;
        this.valueDirection = valueDirection;
        this.valueType = valueType;
        this.entityType = entityType;
        this.entityID = entityID;
        this.cronExpression = cronExpression;
        this.evictionRate = evictionRate;
        this.evictionType = evictionType;
        this.esperRequest = esperRequest;
    }
    
    
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kom_kpi.id
     * 
     * @return the value of kom_kpi.id
     * @mbggenerated Wed Feb 05 15:26:17 CET 2014
     */
    public String computeKPIEsperKey(final IEntity _entity) {
    
    
        return "KPI_"
                + getKpiKey() + "_T_" + getEntityType().ordinal() + "_ENTITY_" + _entity.getId();
    }
    
    
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kom_kpi.cronExpression
     * 
     * @return the value of kom_kpi.cronExpression
     * @mbggenerated Wed Feb 05 15:26:17 CET 2014
     */
    public String getCronExpression() {
    
    
        return cronExpression;
    }
    
    
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kom_kpi.id
     * 
     * @param id
     *            the value for kom_kpi.id
     * @mbggenerated Wed Feb 05 15:26:17 CET 2014
     */
    public String getCronHistoryJobName(final IEntity _entity) {
    
    
        return "HISTORY_" + computeKPIEsperKey(_entity);
    }
    
    
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kom_kpi.description
     * 
     * @return the value of kom_kpi.description
     * @mbggenerated Wed Feb 05 15:26:17 CET 2014
     */
    public String getDescription() {
    
    
        return description;
    }
    
    
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kom_kpi.entityID
     * 
     * @return the value of kom_kpi.entityID
     * @mbggenerated Wed Feb 05 15:26:17 CET 2014
     */
    public Integer getEntityID() {
    
    
        return entityID;
    }
    
    
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kom_kpi.entityType
     * 
     * @return the value of kom_kpi.entityType
     * @mbggenerated Wed Feb 05 15:26:17 CET 2014
     */
    public EntityType getEntityType() {
    
    
        return entityType;
    }
    
    
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kom_kpi.esperRequest
     * 
     * @return the value of kom_kpi.esperRequest
     * @mbggenerated Wed Feb 05 15:26:17 CET 2014
     */
    public String getEsperRequest() {
    
    
        return esperRequest;
    }
    
    
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kom_kpi.evictionRate
     * 
     * @return the value of kom_kpi.evictionRate
     * @mbggenerated Wed Feb 05 15:26:17 CET 2014
     */
    public Integer getEvictionRate() {
    
    
        return evictionRate;
    }
    
    
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kom_kpi.evictionType
     * 
     * @return the value of kom_kpi.evictionType
     * @mbggenerated Wed Feb 05 15:26:17 CET 2014
     */
    public EvictionType getEvictionType() {
    
    
        return evictionType;
    }
    
    
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kom_kpi.idProvider
     * 
     * @return the value of kom_kpi.idProvider
     * @mbggenerated Wed Feb 05 15:26:17 CET 2014
     */
    public Integer getIdProvider() {
    
    
        return idProvider;
    }
    
    
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kom_kpi.kpiKey
     * 
     * @return the value of kom_kpi.kpiKey
     * @mbggenerated Wed Feb 05 15:26:17 CET 2014
     */
    public String getKpiKey() {
    
    
        return kpiKey;
    }
    
    
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kom_kpi.maxValue
     * 
     * @return the value of kom_kpi.maxValue
     * @mbggenerated Wed Feb 05 15:26:17 CET 2014
     */
    public Double getMaxValue() {
    
    
        return maxValue;
    }
    
    
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kom_kpi.minValue
     * 
     * @return the value of kom_kpi.minValue
     * @mbggenerated Wed Feb 05 15:26:17 CET 2014
     */
    public Double getMinValue() {
    
    
        return minValue;
    }
    
    
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kom_kpi.name
     * 
     * @return the value of kom_kpi.name
     * @mbggenerated Wed Feb 05 15:26:17 CET 2014
     */
    public String getName() {
    
    
        return name;
    }
    
    
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kom_kpi.valueDirection
     * 
     * @return the value of kom_kpi.valueDirection
     * @mbggenerated Wed Feb 05 15:26:17 CET 2014
     */
    public ValueDirection getValueDirection() {
    
    
        return valueDirection;
    }
    
    
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kom_kpi.valueType
     * 
     * @return the value of kom_kpi.valueType
     * @mbggenerated Wed Feb 05 15:26:17 CET 2014
     */
    public ValueType getValueType() {
    
    
        return valueType;
    }
    
    
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kom_kpi.cronExpression
     * 
     * @param cronExpression
     *            the value for kom_kpi.cronExpression
     * @mbggenerated Wed Feb 05 15:26:17 CET 2014
     */
    public void setCronExpression(final String cronExpression) {
    
    
        this.cronExpression = cronExpression;
    }
    
    
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kom_kpi.description
     * 
     * @param description
     *            the value for kom_kpi.description
     * @mbggenerated Wed Feb 05 15:26:17 CET 2014
     */
    public void setDescription(final String description) {
    
    
        this.description = description;
    }
    
    
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kom_kpi.entityID
     * 
     * @param entityID
     *            the value for kom_kpi.entityID
     * @mbggenerated Wed Feb 05 15:26:17 CET 2014
     */
    public void setEntityID(final Integer entityID) {
    
    
        this.entityID = entityID;
    }
    
    
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kom_kpi.entityType
     * 
     * @param entityType
     *            the value for kom_kpi.entityType
     * @mbggenerated Wed Feb 05 15:26:17 CET 2014
     */
    public void setEntityType(final EntityType entityType) {
    
    
        this.entityType = entityType;
    }
    
    
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kom_kpi.esperRequest
     * 
     * @param esperRequest
     *            the value for kom_kpi.esperRequest
     * @mbggenerated Wed Feb 05 15:26:17 CET 2014
     */
    public void setEsperRequest(final String esperRequest) {
    
    
        this.esperRequest = esperRequest;
    }
    
    
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kom_kpi.evictionRate
     * 
     * @param evictionRate
     *            the value for kom_kpi.evictionRate
     * @mbggenerated Wed Feb 05 15:26:17 CET 2014
     */
    public void setEvictionRate(final Integer evictionRate) {
    
    
        this.evictionRate = evictionRate;
    }
    
    
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kom_kpi.evictionType
     * 
     * @param evictionType
     *            the value for kom_kpi.evictionType
     * @mbggenerated Wed Feb 05 15:26:17 CET 2014
     */
    public void setEvictionType(final EvictionType evictionType) {
    
    
        this.evictionType = evictionType;
    }
    
    
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kom_kpi.idProvider
     * 
     * @param idProvider
     *            the value for kom_kpi.idProvider
     * @mbggenerated Wed Feb 05 15:26:17 CET 2014
     */
    public void setIdProvider(final Integer idProvider) {
    
    
        this.idProvider = idProvider;
    }
    
    
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kom_kpi.kpiKey
     * 
     * @param kpiKey
     *            the value for kom_kpi.kpiKey
     * @mbggenerated Wed Feb 05 15:26:17 CET 2014
     */
    public void setKpiKey(final String kpiKey) {
    
    
        this.kpiKey = kpiKey;
    }
    
    
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kom_kpi.maxValue
     * 
     * @param maxValue
     *            the value for kom_kpi.maxValue
     * @mbggenerated Wed Feb 05 15:26:17 CET 2014
     */
    public void setMaxValue(final Double maxValue) {
    
    
        this.maxValue = maxValue;
    }
    
    
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kom_kpi.minValue
     * 
     * @param minValue
     *            the value for kom_kpi.minValue
     * @mbggenerated Wed Feb 05 15:26:17 CET 2014
     */
    public void setMinValue(final Double minValue) {
    
    
        this.minValue = minValue;
    }
    
    
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kom_kpi.name
     * 
     * @param name
     *            the value for kom_kpi.name
     * @mbggenerated Wed Feb 05 15:26:17 CET 2014
     */
    public void setName(final String name) {
    
    
        this.name = name;
    }
    
    
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kom_kpi.valueDirection
     * 
     * @param valueDirection
     *            the value for kom_kpi.valueDirection
     * @mbggenerated Wed Feb 05 15:26:17 CET 2014
     */
    public void setValueDirection(final ValueDirection valueDirection) {
    
    
        this.valueDirection = valueDirection;
    }
    
    
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kom_kpi.valueType
     * 
     * @param valueType
     *            the value for kom_kpi.valueType
     * @mbggenerated Wed Feb 05 15:26:17 CET 2014
     */
    public void setValueType(final ValueType valueType) {
    
    
        this.valueType = valueType;
    }


    public Integer getId() {
    
    
        return id;
    }


    public void setId(Integer _id) {
    
    
        id = _id;
    }
}
