
package org.komea.product.database.model;



import java.util.Comparator;
import java.util.Date;

import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

import org.codehaus.jackson.annotate.JsonIgnore;
import org.joda.time.DateTime;
import org.komea.product.database.api.IHasKey;
import org.komea.product.database.api.IKeyVisitor;
import org.komea.product.database.enums.EntityType;
import org.komea.product.service.dto.EntityKey;



public class Measure implements IHasKey
{
    
    
    public static Comparator<Measure> DATE_MEASURE     = new Comparator<Measure>()
                                                       {
                                                           
                                                           
                                                           @Override
                                                           public int compare(
                                                                   final Measure _arg0,
                                                                   final Measure _arg1) {
                                                           
                                                           
                                                               return _arg0.getDate().compareTo(
                                                                       _arg1.getDate());
                                                           }
                                                       };
    
    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database table kom_msr
     * 
     * @mbggenerated Tue Feb 11 16:06:30 CET 2014
     */
    private static final long         serialVersionUID = 1L;
    
    
    
    /**
     * This factory method builds a kpi from
     * 
     * @param _kpiKey
     *            KpiKey
     * @return Measure
     */
    public static Measure initializeMeasure(final int _kpiID, final EntityKey _entityKey) {
    
    
        final Measure measure = new Measure();
        measure.setDate(new Date());
        if (_entityKey != null) {
            measure.setEntity(_entityKey.getEntityType(), _entityKey.getId());
        }
        measure.setIdKpi(_kpiID);
        
        return measure;
    }
    
    
    public static Measure initializeMeasure(final Kpi _kpi, final EntityKey _key, final Double value) {
    
    
        final Measure measureKey = Measure.initializeMeasure(_kpi.getId(), _key);
        measureKey.setValue(value);
        return measureKey;
    }
    
    
    
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kom_msr.date
     * 
     * @mbggenerated Thu May 08 13:09:26 CEST 2014
     */
    @NotNull
    private Date    date;
    
    
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kom_msr.day
     * 
     * @mbggenerated Thu May 08 13:09:26 CEST 2014
     */
    @NotNull
    private Integer day;
    
    
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kom_msr.hour
     * 
     * @mbggenerated Thu May 08 13:09:26 CEST 2014
     */
    private Integer hour;
    
    
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kom_msr.id
     * 
     * @mbggenerated Thu May 08 13:09:26 CEST 2014
     */
    private Integer id;
    
    
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kom_msr.idKpi
     * 
     * @mbggenerated Thu May 08 13:09:26 CEST 2014
     */
    private Integer idKpi;
    
    
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kom_msr.idPerson
     * 
     * @mbggenerated Thu May 08 13:09:26 CEST 2014
     */
    private Integer idPerson;
    
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kom_msr.idPersonGroup
     * 
     * @mbggenerated Thu May 08 13:09:26 CEST 2014
     */
    private Integer idPersonGroup;
    
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kom_msr.idProject
     * 
     * @mbggenerated Thu May 08 13:09:26 CEST 2014
     */
    private Integer idProject;
    
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kom_msr.month
     * 
     * @mbggenerated Thu May 08 13:09:26 CEST 2014
     */
    @NotNull
    private Integer month;
    
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kom_msr.sprint
     * 
     * @mbggenerated Thu May 08 13:09:26 CEST 2014
     */
    @Size(min = 0, max = 45)
    private String  sprint;
    
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kom_msr.value
     * 
     * @mbggenerated Thu May 08 13:09:26 CEST 2014
     */
    @NotNull
    private Double  value;
    
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kom_msr.week
     * 
     * @mbggenerated Thu May 08 13:09:26 CEST 2014
     */
    @NotNull
    private Integer week;
    
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kom_msr.year
     * 
     * @mbggenerated Thu May 08 13:09:26 CEST 2014
     */
    @NotNull
    private Integer year;
    
    
    
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kom_msr
     * 
     * @mbggenerated Thu May 08 13:09:26 CEST 2014
     */
    public Measure() {
    
    
        super();
    }
    
    
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kom_msr
     * 
     * @mbggenerated Thu May 08 13:09:26 CEST 2014
     */
    public Measure(
            final Integer id,
            final Integer idKpi,
            final Date date,
            final Integer idProject,
            final Integer idPerson,
            final Integer idPersonGroup,
            final Double value,
            final Integer year,
            final Integer month,
            final Integer week,
            final Integer day,
            final Integer hour,
            final String sprint) {
    
    
        this.id = id;
        this.idKpi = idKpi;
        this.date = date;
        this.idProject = idProject;
        this.idPerson = idPerson;
        this.idPersonGroup = idPersonGroup;
        this.value = value;
        this.year = year;
        this.month = month;
        this.week = week;
        this.day = day;
        this.hour = hour;
        this.sprint = sprint;
    }
    
    
    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table kom_msr
     * 
     * @mbggenerated Tue Feb 11 16:06:30 CET 2014
     */
    public Measure(
            final Integer id,
            final Integer idKpi,
            final DateTime date,
            final Integer idPersonGroup,
            final Integer idPerson,
            final Integer idProject,
            final Double value) {
    
    
        this.id = id;
        this.idKpi = idKpi;
        this.date = date.toDate();
        this.idPersonGroup = idPersonGroup;
        this.idPerson = idPerson;
        this.idProject = idProject;
        this.value = value;
        setDateTime(date);
        sprint = null;
        
    }
    
    
    /*
     * (non-Javadoc)
     * @see
     * org.komea.product.database.api.IHasKey#accept(org.komea.product.database
     * .api.IKeyVisitor)
     */
    @Override
    public void accept(final IKeyVisitor _visitor) {
    
    
        _visitor.visit(this);
        
    }
    
    
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kom_msr.date
     * 
     * @return the value of kom_msr.date
     * @mbggenerated Thu May 08 13:09:26 CEST 2014
     */
    public Date getDate() {
    
    
        return date;
    }
    
    
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kom_msr.day
     * 
     * @return the value of kom_msr.day
     * @mbggenerated Thu May 08 13:09:26 CEST 2014
     */
    public Integer getDay() {
    
    
        return day;
    }
    
    
    @Override
    @JsonIgnore
    public String getDisplayName() {
    
    
        return "";
    }
    
    
    /**
     * Returns an entity key from a measure
     * 
     * @return the entity key
     */
    public Integer getEntityID() {
    
    
        if (idPerson != null) {
            return idPerson;
        }
        if (idPersonGroup != null) {
            return idPersonGroup;
        }
        if (idProject != null) {
            return idProject;
        }
        return null;
        
    }
    
    
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kom_msr.hour
     * 
     * @return the value of kom_msr.hour
     * @mbggenerated Thu May 08 13:09:26 CEST 2014
     */
    public Integer getHour() {
    
    
        return hour;
    }
    
    
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kom_msr.id
     * 
     * @return the value of kom_msr.id
     * @mbggenerated Thu May 08 13:09:26 CEST 2014
     */
    @Override
    public Integer getId() {
    
    
        return id;
    }
    
    
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kom_msr.idKpi
     * 
     * @return the value of kom_msr.idKpi
     * @mbggenerated Thu May 08 13:09:26 CEST 2014
     */
    public Integer getIdKpi() {
    
    
        return idKpi;
    }
    
    
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kom_msr.idPerson
     * 
     * @return the value of kom_msr.idPerson
     * @mbggenerated Thu May 08 13:09:26 CEST 2014
     */
    public Integer getIdPerson() {
    
    
        return idPerson;
    }
    
    
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kom_msr.idPersonGroup
     * 
     * @return the value of kom_msr.idPersonGroup
     * @mbggenerated Thu May 08 13:09:26 CEST 2014
     */
    public Integer getIdPersonGroup() {
    
    
        return idPersonGroup;
    }
    
    
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kom_msr.idProject
     * 
     * @return the value of kom_msr.idProject
     * @mbggenerated Thu May 08 13:09:26 CEST 2014
     */
    public Integer getIdProject() {
    
    
        return idProject;
    }
    
    
    @Override
    @JsonIgnore
    public String getKey() {
    
    
        return "";
    }
    
    
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kom_msr.month
     * 
     * @return the value of kom_msr.month
     * @mbggenerated Thu May 08 13:09:26 CEST 2014
     */
    public Integer getMonth() {
    
    
        return month;
    }
    
    
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kom_msr.sprint
     * 
     * @return the value of kom_msr.sprint
     * @mbggenerated Thu May 08 13:09:26 CEST 2014
     */
    public String getSprint() {
    
    
        return sprint;
    }
    
    
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kom_msr.value
     * 
     * @return the value of kom_msr.value
     * @mbggenerated Thu May 08 13:09:26 CEST 2014
     */
    public Double getValue() {
    
    
        return value;
    }
    
    
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kom_msr.week
     * 
     * @return the value of kom_msr.week
     * @mbggenerated Thu May 08 13:09:26 CEST 2014
     */
    public Integer getWeek() {
    
    
        return week;
    }
    
    
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kom_msr.year
     * 
     * @return the value of kom_msr.year
     * @mbggenerated Thu May 08 13:09:26 CEST 2014
     */
    public Integer getYear() {
    
    
        return year;
    }
    
    
    @JsonIgnore
    public boolean isValid() {
    
    
        return value != null && !value.isInfinite() && !value.isNaN();
    }
    
    
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kom_msr.date
     * 
     * @param date
     *            the value for kom_msr.date
     * @mbggenerated Thu May 08 13:09:26 CEST 2014
     */
    public void setDate(final Date date) {
    
    
        this.date = date;
    }
    
    
    public void setDateTime(final DateTime _date) {
    
    
        date = _date.toDate();
        year = _date.getYear();
        month = _date.getMonthOfYear();
        week = _date.getWeekOfWeekyear();
        day = _date.getDayOfMonth();
        hour = _date.getHourOfDay();
    }
    
    
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kom_msr.day
     * 
     * @param day
     *            the value for kom_msr.day
     * @mbggenerated Thu May 08 13:09:26 CEST 2014
     */
    public void setDay(final Integer day) {
    
    
        this.day = day;
    }
    
    
    public void setEntity(final EntityType _entityType, final Integer _entityID) {
    
    
        if (_entityType == null || _entityID == null) {
            return;
        }
        switch (_entityType) {
            case PERSON:
                setIdPerson(_entityID);
                break;
            case DEPARTMENT:
            case TEAM:
                setIdPersonGroup(_entityID);
                break;
            case PROJECT:
                setIdProject(_entityID);
                break;
            default:
                break;
        
        }
        
    }
    
    
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kom_msr.hour
     * 
     * @param hour
     *            the value for kom_msr.hour
     * @mbggenerated Thu May 08 13:09:26 CEST 2014
     */
    public void setHour(final Integer hour) {
    
    
        this.hour = hour;
    }
    
    
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kom_msr.id
     * 
     * @param id
     *            the value for kom_msr.id
     * @mbggenerated Thu May 08 13:09:26 CEST 2014
     */
    @Override
    public void setId(final Integer id) {
    
    
        this.id = id;
    }
    
    
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kom_msr.idKpi
     * 
     * @param idKpi
     *            the value for kom_msr.idKpi
     * @mbggenerated Thu May 08 13:09:26 CEST 2014
     */
    public void setIdKpi(final Integer idKpi) {
    
    
        this.idKpi = idKpi;
    }
    
    
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kom_msr.idPerson
     * 
     * @param idPerson
     *            the value for kom_msr.idPerson
     * @mbggenerated Thu May 08 13:09:26 CEST 2014
     */
    public void setIdPerson(final Integer idPerson) {
    
    
        this.idPerson = idPerson;
    }
    
    
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kom_msr.idPersonGroup
     * 
     * @param idPersonGroup
     *            the value for kom_msr.idPersonGroup
     * @mbggenerated Thu May 08 13:09:26 CEST 2014
     */
    public void setIdPersonGroup(final Integer idPersonGroup) {
    
    
        this.idPersonGroup = idPersonGroup;
    }
    
    
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kom_msr.idProject
     * 
     * @param idProject
     *            the value for kom_msr.idProject
     * @mbggenerated Thu May 08 13:09:26 CEST 2014
     */
    public void setIdProject(final Integer idProject) {
    
    
        this.idProject = idProject;
    }
    
    
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kom_msr.month
     * 
     * @param month
     *            the value for kom_msr.month
     * @mbggenerated Thu May 08 13:09:26 CEST 2014
     */
    public void setMonth(final Integer month) {
    
    
        this.month = month;
    }
    
    
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kom_msr.sprint
     * 
     * @param sprint
     *            the value for kom_msr.sprint
     * @mbggenerated Thu May 08 13:09:26 CEST 2014
     */
    public void setSprint(final String sprint) {
    
    
        this.sprint = sprint;
    }
    
    
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kom_msr.value
     * 
     * @param value
     *            the value for kom_msr.value
     * @mbggenerated Thu May 08 13:09:26 CEST 2014
     */
    public void setValue(final Double value) {
    
    
        this.value = value;
    }
    
    
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kom_msr.week
     * 
     * @param week
     *            the value for kom_msr.week
     * @mbggenerated Thu May 08 13:09:26 CEST 2014
     */
    public void setWeek(final Integer week) {
    
    
        this.week = week;
    }
    
    
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kom_msr.year
     * 
     * @param year
     *            the value for kom_msr.year
     * @mbggenerated Thu May 08 13:09:26 CEST 2014
     */
    public void setYear(final Integer year) {
    
    
        this.year = year;
    }
    
    
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kom_msr
     * 
     * @mbggenerated Thu May 08 13:09:26 CEST 2014
     */
    @Override
    public String toString() {
    
    
        final StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", idKpi=").append(idKpi);
        sb.append(", date=").append(date);
        sb.append(", idProject=").append(idProject);
        sb.append(", idPerson=").append(idPerson);
        sb.append(", idPersonGroup=").append(idPersonGroup);
        sb.append(", value=").append(value);
        sb.append(", year=").append(year);
        sb.append(", month=").append(month);
        sb.append(", week=").append(week);
        sb.append(", day=").append(day);
        sb.append(", hour=").append(hour);
        sb.append(", sprint=").append(sprint);
        sb.append("]");
        return sb.toString();
    }
    
}
