package org.komea.product.database.model;

import java.io.Serializable;
import javax.validation.constraints.NotNull;

public class MeasureKey implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kom_msr.idKpi
     *
     * @mbggenerated Thu May 08 17:54:52 CEST 2014
     */
    private Integer idKpi;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kom_msr.year
     *
     * @mbggenerated Thu May 08 17:54:52 CEST 2014
     */
    @NotNull
    private Integer year;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kom_msr.month
     *
     * @mbggenerated Thu May 08 17:54:52 CEST 2014
     */
    @NotNull
    private Integer month;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kom_msr.week
     *
     * @mbggenerated Thu May 08 17:54:52 CEST 2014
     */
    @NotNull
    private Integer week;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kom_msr.day
     *
     * @mbggenerated Thu May 08 17:54:52 CEST 2014
     */
    @NotNull
    private Integer day;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kom_msr.hour
     *
     * @mbggenerated Thu May 08 17:54:52 CEST 2014
     */
    @NotNull
    private Integer hour;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kom_msr.entityID
     *
     * @mbggenerated Thu May 08 17:54:52 CEST 2014
     */
    @NotNull
    private Integer entityID;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table kom_msr
     *
     * @mbggenerated Thu May 08 17:54:52 CEST 2014
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kom_msr
     *
     * @mbggenerated Thu May 08 17:54:52 CEST 2014
     */
    public MeasureKey(Integer idKpi, Integer year, Integer month, Integer week, Integer day, Integer hour, Integer entityID) {
        this.idKpi = idKpi;
        this.year = year;
        this.month = month;
        this.week = week;
        this.day = day;
        this.hour = hour;
        this.entityID = entityID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kom_msr
     *
     * @mbggenerated Thu May 08 17:54:52 CEST 2014
     */
    public MeasureKey() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kom_msr.idKpi
     *
     * @return the value of kom_msr.idKpi
     *
     * @mbggenerated Thu May 08 17:54:52 CEST 2014
     */
    public Integer getIdKpi() {
        return idKpi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kom_msr.idKpi
     *
     * @param idKpi the value for kom_msr.idKpi
     *
     * @mbggenerated Thu May 08 17:54:52 CEST 2014
     */
    public void setIdKpi(Integer idKpi) {
        this.idKpi = idKpi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kom_msr.year
     *
     * @return the value of kom_msr.year
     *
     * @mbggenerated Thu May 08 17:54:52 CEST 2014
     */
    public Integer getYear() {
        return year;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kom_msr.year
     *
     * @param year the value for kom_msr.year
     *
     * @mbggenerated Thu May 08 17:54:52 CEST 2014
     */
    public void setYear(Integer year) {
        this.year = year;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kom_msr.month
     *
     * @return the value of kom_msr.month
     *
     * @mbggenerated Thu May 08 17:54:52 CEST 2014
     */
    public Integer getMonth() {
        return month;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kom_msr.month
     *
     * @param month the value for kom_msr.month
     *
     * @mbggenerated Thu May 08 17:54:52 CEST 2014
     */
    public void setMonth(Integer month) {
        this.month = month;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kom_msr.week
     *
     * @return the value of kom_msr.week
     *
     * @mbggenerated Thu May 08 17:54:52 CEST 2014
     */
    public Integer getWeek() {
        return week;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kom_msr.week
     *
     * @param week the value for kom_msr.week
     *
     * @mbggenerated Thu May 08 17:54:52 CEST 2014
     */
    public void setWeek(Integer week) {
        this.week = week;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kom_msr.day
     *
     * @return the value of kom_msr.day
     *
     * @mbggenerated Thu May 08 17:54:52 CEST 2014
     */
    public Integer getDay() {
        return day;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kom_msr.day
     *
     * @param day the value for kom_msr.day
     *
     * @mbggenerated Thu May 08 17:54:52 CEST 2014
     */
    public void setDay(Integer day) {
        this.day = day;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kom_msr.hour
     *
     * @return the value of kom_msr.hour
     *
     * @mbggenerated Thu May 08 17:54:52 CEST 2014
     */
    public Integer getHour() {
        return hour;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kom_msr.hour
     *
     * @param hour the value for kom_msr.hour
     *
     * @mbggenerated Thu May 08 17:54:52 CEST 2014
     */
    public void setHour(Integer hour) {
        this.hour = hour;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kom_msr.entityID
     *
     * @return the value of kom_msr.entityID
     *
     * @mbggenerated Thu May 08 17:54:52 CEST 2014
     */
    public Integer getEntityID() {
        return entityID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kom_msr.entityID
     *
     * @param entityID the value for kom_msr.entityID
     *
     * @mbggenerated Thu May 08 17:54:52 CEST 2014
     */
    public void setEntityID(Integer entityID) {
        this.entityID = entityID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kom_msr
     *
     * @mbggenerated Thu May 08 17:54:52 CEST 2014
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", idKpi=").append(idKpi);
        sb.append(", year=").append(year);
        sb.append(", month=").append(month);
        sb.append(", week=").append(week);
        sb.append(", day=").append(day);
        sb.append(", hour=").append(hour);
        sb.append(", entityID=").append(entityID);
        sb.append("]");
        return sb.toString();
    }
}