package org.komea.product.database.model;

import java.io.Serializable;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;
import org.komea.product.database.api.IEntity;
import org.komea.product.database.enums.EntityType;
import org.komea.product.database.enums.PersonGroupType;

public class PersonGroup implements IEntity, Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kom_pegr.id
     *
     * @mbggenerated Tue Feb 11 15:35:54 CET 2014
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kom_pegr.name
     *
     * @mbggenerated Tue Feb 11 15:35:54 CET 2014
     */
    @NotNull
    @Size(min = 0, max = 255)
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kom_pegr.personGroupKey
     *
     * @mbggenerated Tue Feb 11 15:35:54 CET 2014
     */
    @NotNull
    @Size(min = 0, max = 255)
    private String personGroupKey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kom_pegr.description
     *
     * @mbggenerated Tue Feb 11 15:35:54 CET 2014
     */
    @Size(min = 0, max = 2048)
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kom_pegr.idPersonGroupParent
     *
     * @mbggenerated Tue Feb 11 15:35:54 CET 2014
     */
    private Integer idPersonGroupParent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kom_pegr.idGroupKind
     *
     * @mbggenerated Tue Feb 11 15:35:54 CET 2014
     */
    private Integer idGroupKind;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kom_pegr.type
     *
     * @mbggenerated Tue Feb 11 15:35:54 CET 2014
     */
    @NotNull
    private PersonGroupType type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table kom_pegr
     *
     * @mbggenerated Tue Feb 11 15:35:54 CET 2014
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kom_pegr
     *
     * @mbggenerated Tue Feb 11 15:35:54 CET 2014
     */
    public PersonGroup(Integer id, String name, String personGroupKey, String description, Integer idPersonGroupParent, Integer idGroupKind, PersonGroupType type) {
        this.id = id;
        this.name = name;
        this.personGroupKey = personGroupKey;
        this.description = description;
        this.idPersonGroupParent = idPersonGroupParent;
        this.idGroupKind = idGroupKind;
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kom_pegr
     *
     * @mbggenerated Tue Feb 11 15:35:54 CET 2014
     */
    public PersonGroup() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kom_pegr.id
     *
     * @return the value of kom_pegr.id
     *
     * @mbggenerated Tue Feb 11 15:35:54 CET 2014
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kom_pegr.id
     *
     * @param id the value for kom_pegr.id
     *
     * @mbggenerated Tue Feb 11 15:35:54 CET 2014
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kom_pegr.name
     *
     * @return the value of kom_pegr.name
     *
     * @mbggenerated Tue Feb 11 15:35:54 CET 2014
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kom_pegr.name
     *
     * @param name the value for kom_pegr.name
     *
     * @mbggenerated Tue Feb 11 15:35:54 CET 2014
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kom_pegr.personGroupKey
     *
     * @return the value of kom_pegr.personGroupKey
     *
     * @mbggenerated Tue Feb 11 15:35:54 CET 2014
     */
    public String getPersonGroupKey() {
        return personGroupKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kom_pegr.personGroupKey
     *
     * @param personGroupKey the value for kom_pegr.personGroupKey
     *
     * @mbggenerated Tue Feb 11 15:35:54 CET 2014
     */
    public void setPersonGroupKey(String personGroupKey) {
        this.personGroupKey = personGroupKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kom_pegr.description
     *
     * @return the value of kom_pegr.description
     *
     * @mbggenerated Tue Feb 11 15:35:54 CET 2014
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kom_pegr.description
     *
     * @param description the value for kom_pegr.description
     *
     * @mbggenerated Tue Feb 11 15:35:54 CET 2014
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kom_pegr.idPersonGroupParent
     *
     * @return the value of kom_pegr.idPersonGroupParent
     *
     * @mbggenerated Tue Feb 11 15:35:54 CET 2014
     */
    public Integer getIdPersonGroupParent() {
        return idPersonGroupParent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kom_pegr.idPersonGroupParent
     *
     * @param idPersonGroupParent the value for kom_pegr.idPersonGroupParent
     *
     * @mbggenerated Tue Feb 11 15:35:54 CET 2014
     */
    public void setIdPersonGroupParent(Integer idPersonGroupParent) {
        this.idPersonGroupParent = idPersonGroupParent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kom_pegr.idGroupKind
     *
     * @return the value of kom_pegr.idGroupKind
     *
     * @mbggenerated Tue Feb 11 15:35:54 CET 2014
     */
    public Integer getIdGroupKind() {
        return idGroupKind;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kom_pegr.idGroupKind
     *
     * @param idGroupKind the value for kom_pegr.idGroupKind
     *
     * @mbggenerated Tue Feb 11 15:35:54 CET 2014
     */
    public void setIdGroupKind(Integer idGroupKind) {
        this.idGroupKind = idGroupKind;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kom_pegr.type
     *
     * @return the value of kom_pegr.type
     *
     * @mbggenerated Tue Feb 11 15:35:54 CET 2014
     */
    public PersonGroupType getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kom_pegr.type
     *
     * @param type the value for kom_pegr.type
     *
     * @mbggenerated Tue Feb 11 15:35:54 CET 2014
     */
    public void setType(PersonGroupType type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kom_pegr
     *
     * @mbggenerated Tue Feb 11 15:35:54 CET 2014
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", name=").append(name);
        sb.append(", personGroupKey=").append(personGroupKey);
        sb.append(", description=").append(description);
        sb.append(", idPersonGroupParent=").append(idPersonGroupParent);
        sb.append(", idGroupKind=").append(idGroupKind);
        sb.append(", type=").append(type);
        sb.append("]");
        return sb.toString();
    }

    @Override
    public EntityType entityType() {
        return EntityType.PERSON_GROUP;
    }
}