package org.komea.product.database.model;

import java.util.ArrayList;
import java.util.List;

public class PersonGroupCriteria {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table kom_pegr
     *
     * @mbggenerated Wed Feb 05 10:10:36 CET 2014
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table kom_pegr
     *
     * @mbggenerated Wed Feb 05 10:10:36 CET 2014
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table kom_pegr
     *
     * @mbggenerated Wed Feb 05 10:10:36 CET 2014
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kom_pegr
     *
     * @mbggenerated Wed Feb 05 10:10:36 CET 2014
     */
    public PersonGroupCriteria() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kom_pegr
     *
     * @mbggenerated Wed Feb 05 10:10:36 CET 2014
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kom_pegr
     *
     * @mbggenerated Wed Feb 05 10:10:36 CET 2014
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kom_pegr
     *
     * @mbggenerated Wed Feb 05 10:10:36 CET 2014
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kom_pegr
     *
     * @mbggenerated Wed Feb 05 10:10:36 CET 2014
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kom_pegr
     *
     * @mbggenerated Wed Feb 05 10:10:36 CET 2014
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kom_pegr
     *
     * @mbggenerated Wed Feb 05 10:10:36 CET 2014
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kom_pegr
     *
     * @mbggenerated Wed Feb 05 10:10:36 CET 2014
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kom_pegr
     *
     * @mbggenerated Wed Feb 05 10:10:36 CET 2014
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kom_pegr
     *
     * @mbggenerated Wed Feb 05 10:10:36 CET 2014
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kom_pegr
     *
     * @mbggenerated Wed Feb 05 10:10:36 CET 2014
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table kom_pegr
     *
     * @mbggenerated Wed Feb 05 10:10:36 CET 2014
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andNameIsNull() {
            addCriterion("name is null");
            return (Criteria) this;
        }

        public Criteria andNameIsNotNull() {
            addCriterion("name is not null");
            return (Criteria) this;
        }

        public Criteria andNameEqualTo(String value) {
            addCriterion("name =", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotEqualTo(String value) {
            addCriterion("name <>", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThan(String value) {
            addCriterion("name >", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThanOrEqualTo(String value) {
            addCriterion("name >=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThan(String value) {
            addCriterion("name <", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThanOrEqualTo(String value) {
            addCriterion("name <=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLike(String value) {
            addCriterion("name like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotLike(String value) {
            addCriterion("name not like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameIn(List<String> values) {
            addCriterion("name in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotIn(List<String> values) {
            addCriterion("name not in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameBetween(String value1, String value2) {
            addCriterion("name between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotBetween(String value1, String value2) {
            addCriterion("name not between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andPersonGroupKeyIsNull() {
            addCriterion("personGroupKey is null");
            return (Criteria) this;
        }

        public Criteria andPersonGroupKeyIsNotNull() {
            addCriterion("personGroupKey is not null");
            return (Criteria) this;
        }

        public Criteria andPersonGroupKeyEqualTo(String value) {
            addCriterion("personGroupKey =", value, "personGroupKey");
            return (Criteria) this;
        }

        public Criteria andPersonGroupKeyNotEqualTo(String value) {
            addCriterion("personGroupKey <>", value, "personGroupKey");
            return (Criteria) this;
        }

        public Criteria andPersonGroupKeyGreaterThan(String value) {
            addCriterion("personGroupKey >", value, "personGroupKey");
            return (Criteria) this;
        }

        public Criteria andPersonGroupKeyGreaterThanOrEqualTo(String value) {
            addCriterion("personGroupKey >=", value, "personGroupKey");
            return (Criteria) this;
        }

        public Criteria andPersonGroupKeyLessThan(String value) {
            addCriterion("personGroupKey <", value, "personGroupKey");
            return (Criteria) this;
        }

        public Criteria andPersonGroupKeyLessThanOrEqualTo(String value) {
            addCriterion("personGroupKey <=", value, "personGroupKey");
            return (Criteria) this;
        }

        public Criteria andPersonGroupKeyLike(String value) {
            addCriterion("personGroupKey like", value, "personGroupKey");
            return (Criteria) this;
        }

        public Criteria andPersonGroupKeyNotLike(String value) {
            addCriterion("personGroupKey not like", value, "personGroupKey");
            return (Criteria) this;
        }

        public Criteria andPersonGroupKeyIn(List<String> values) {
            addCriterion("personGroupKey in", values, "personGroupKey");
            return (Criteria) this;
        }

        public Criteria andPersonGroupKeyNotIn(List<String> values) {
            addCriterion("personGroupKey not in", values, "personGroupKey");
            return (Criteria) this;
        }

        public Criteria andPersonGroupKeyBetween(String value1, String value2) {
            addCriterion("personGroupKey between", value1, value2, "personGroupKey");
            return (Criteria) this;
        }

        public Criteria andPersonGroupKeyNotBetween(String value1, String value2) {
            addCriterion("personGroupKey not between", value1, value2, "personGroupKey");
            return (Criteria) this;
        }

        public Criteria andDescriptionIsNull() {
            addCriterion("description is null");
            return (Criteria) this;
        }

        public Criteria andDescriptionIsNotNull() {
            addCriterion("description is not null");
            return (Criteria) this;
        }

        public Criteria andDescriptionEqualTo(String value) {
            addCriterion("description =", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionNotEqualTo(String value) {
            addCriterion("description <>", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionGreaterThan(String value) {
            addCriterion("description >", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionGreaterThanOrEqualTo(String value) {
            addCriterion("description >=", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionLessThan(String value) {
            addCriterion("description <", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionLessThanOrEqualTo(String value) {
            addCriterion("description <=", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionLike(String value) {
            addCriterion("description like", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionNotLike(String value) {
            addCriterion("description not like", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionIn(List<String> values) {
            addCriterion("description in", values, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionNotIn(List<String> values) {
            addCriterion("description not in", values, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionBetween(String value1, String value2) {
            addCriterion("description between", value1, value2, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionNotBetween(String value1, String value2) {
            addCriterion("description not between", value1, value2, "description");
            return (Criteria) this;
        }

        public Criteria andIdPersonGroupParentIsNull() {
            addCriterion("idPersonGroupParent is null");
            return (Criteria) this;
        }

        public Criteria andIdPersonGroupParentIsNotNull() {
            addCriterion("idPersonGroupParent is not null");
            return (Criteria) this;
        }

        public Criteria andIdPersonGroupParentEqualTo(Integer value) {
            addCriterion("idPersonGroupParent =", value, "idPersonGroupParent");
            return (Criteria) this;
        }

        public Criteria andIdPersonGroupParentNotEqualTo(Integer value) {
            addCriterion("idPersonGroupParent <>", value, "idPersonGroupParent");
            return (Criteria) this;
        }

        public Criteria andIdPersonGroupParentGreaterThan(Integer value) {
            addCriterion("idPersonGroupParent >", value, "idPersonGroupParent");
            return (Criteria) this;
        }

        public Criteria andIdPersonGroupParentGreaterThanOrEqualTo(Integer value) {
            addCriterion("idPersonGroupParent >=", value, "idPersonGroupParent");
            return (Criteria) this;
        }

        public Criteria andIdPersonGroupParentLessThan(Integer value) {
            addCriterion("idPersonGroupParent <", value, "idPersonGroupParent");
            return (Criteria) this;
        }

        public Criteria andIdPersonGroupParentLessThanOrEqualTo(Integer value) {
            addCriterion("idPersonGroupParent <=", value, "idPersonGroupParent");
            return (Criteria) this;
        }

        public Criteria andIdPersonGroupParentIn(List<Integer> values) {
            addCriterion("idPersonGroupParent in", values, "idPersonGroupParent");
            return (Criteria) this;
        }

        public Criteria andIdPersonGroupParentNotIn(List<Integer> values) {
            addCriterion("idPersonGroupParent not in", values, "idPersonGroupParent");
            return (Criteria) this;
        }

        public Criteria andIdPersonGroupParentBetween(Integer value1, Integer value2) {
            addCriterion("idPersonGroupParent between", value1, value2, "idPersonGroupParent");
            return (Criteria) this;
        }

        public Criteria andIdPersonGroupParentNotBetween(Integer value1, Integer value2) {
            addCriterion("idPersonGroupParent not between", value1, value2, "idPersonGroupParent");
            return (Criteria) this;
        }

        public Criteria andIdGroupKindIsNull() {
            addCriterion("idGroupKind is null");
            return (Criteria) this;
        }

        public Criteria andIdGroupKindIsNotNull() {
            addCriterion("idGroupKind is not null");
            return (Criteria) this;
        }

        public Criteria andIdGroupKindEqualTo(Integer value) {
            addCriterion("idGroupKind =", value, "idGroupKind");
            return (Criteria) this;
        }

        public Criteria andIdGroupKindNotEqualTo(Integer value) {
            addCriterion("idGroupKind <>", value, "idGroupKind");
            return (Criteria) this;
        }

        public Criteria andIdGroupKindGreaterThan(Integer value) {
            addCriterion("idGroupKind >", value, "idGroupKind");
            return (Criteria) this;
        }

        public Criteria andIdGroupKindGreaterThanOrEqualTo(Integer value) {
            addCriterion("idGroupKind >=", value, "idGroupKind");
            return (Criteria) this;
        }

        public Criteria andIdGroupKindLessThan(Integer value) {
            addCriterion("idGroupKind <", value, "idGroupKind");
            return (Criteria) this;
        }

        public Criteria andIdGroupKindLessThanOrEqualTo(Integer value) {
            addCriterion("idGroupKind <=", value, "idGroupKind");
            return (Criteria) this;
        }

        public Criteria andIdGroupKindIn(List<Integer> values) {
            addCriterion("idGroupKind in", values, "idGroupKind");
            return (Criteria) this;
        }

        public Criteria andIdGroupKindNotIn(List<Integer> values) {
            addCriterion("idGroupKind not in", values, "idGroupKind");
            return (Criteria) this;
        }

        public Criteria andIdGroupKindBetween(Integer value1, Integer value2) {
            addCriterion("idGroupKind between", value1, value2, "idGroupKind");
            return (Criteria) this;
        }

        public Criteria andIdGroupKindNotBetween(Integer value1, Integer value2) {
            addCriterion("idGroupKind not between", value1, value2, "idGroupKind");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table kom_pegr
     *
     * @mbggenerated do_not_delete_during_merge Wed Feb 05 10:10:36 CET 2014
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table kom_pegr
     *
     * @mbggenerated Wed Feb 05 10:10:36 CET 2014
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}