package org.komea.product.database.model;

import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;
import org.komea.product.database.api.IEntity;
import org.komea.product.database.api.IKeyVisitor;
import org.komea.product.database.enums.EntityType;
import org.komea.product.service.dto.EntityKey;

public class Project implements IEntity {

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database table kom_proj
     *
     * @mbggenerated Thu Mar 06 10:32:30 CET 2014
     */
    private static final long serialVersionUID = 1L;

    private static final char ALIAS_SEPARATOR = ';';

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column kom_proj.description
     *
     * @mbggenerated Thu Mar 06 10:32:30 CET 2014
     */
    @Size(min = 0, max = 2048)
    private String description;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column kom_proj.icon
     *
     * @mbggenerated Thu Mar 06 10:32:30 CET 2014
     */
    @Size(min = 0, max = 255)
    private String icon;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column kom_proj.id
     *
     * @mbggenerated Thu Mar 06 10:32:30 CET 2014
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column kom_proj.idCustomer
     *
     * @mbggenerated Thu Mar 06 10:32:30 CET 2014
     */
    private Integer idCustomer;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column kom_proj.name
     *
     * @mbggenerated Thu Mar 06 10:32:30 CET 2014
     */
    @NotNull
    @Size(min = 0, max = 255)
    private String name;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column kom_proj.projectKey
     *
     * @mbggenerated Thu Mar 06 10:32:30 CET 2014
     */
    @NotNull
    @Size(min = 0, max = 255)
    private String projectKey;

    @NotNull
    @Size(min = 0, max = 2048)
    private String alias = "";

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table kom_proj
     *
     * @mbggenerated Thu Mar 06 10:32:30 CET 2014
     */
    public Project() {

        super();
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table kom_proj
     *
     * @mbggenerated Thu Mar 06 10:32:30 CET 2014
     */
    public Project(
            final Integer id,
            final String projectKey,
            final String name,
            final String description,
            final Integer idCustomer,
            final String icon,
            final String alias) {

        this.id = id;
        this.projectKey = projectKey;
        this.name = name;
        this.description = description;
        this.idCustomer = idCustomer;
        this.icon = icon;
        this.alias = alias;
    }

    public Project(
            final Integer id,
            final String projectKey,
            final String name,
            final String description,
            final Integer idCustomer,
            final String icon) {

        this.id = id;
        this.projectKey = projectKey;
        this.name = name;
        this.description = description;
        this.idCustomer = idCustomer;
        this.icon = icon;
        this.alias = "";
    }

    /*
     * (non-Javadoc)
     * @see org.komea.product.database.api.IHasKey#accept(org.komea.product.database.api.IKeyVisitor)
     */
    @Override
    public void accept(final IKeyVisitor _visitor) {

        _visitor.visit(this);

    }

    @Override
    public EntityType entityType() {

        return EntityType.PROJECT;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column kom_proj.description
     *
     * @return the value of kom_proj.description
     * @mbggenerated Thu Mar 06 10:32:30 CET 2014
     */
    public String getDescription() {

        return description;
    }

    @Override
    public String getDisplayName() {

        return name;
    }

    /*
     * (non-Javadoc)
     * @see org.komea.product.database.api.IEntity#getKey()
     */
    @Override
    public EntityKey getEntityKey() {

        return new EntityKey(entityType(), getId());
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column kom_proj.icon
     *
     * @return the value of kom_proj.icon
     * @mbggenerated Thu Mar 06 10:32:30 CET 2014
     */
    public String getIcon() {

        return icon;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column kom_proj.id
     *
     * @return the value of kom_proj.id
     * @mbggenerated Thu Mar 06 10:32:30 CET 2014
     */
    @Override
    public Integer getId() {

        return id;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column kom_proj.idCustomer
     *
     * @return the value of kom_proj.idCustomer
     * @mbggenerated Thu Mar 06 10:32:30 CET 2014
     */
    public Integer getIdCustomer() {

        return idCustomer;
    }

    @Override
    public String getKey() {

        return projectKey;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column kom_proj.name
     *
     * @return the value of kom_proj.name
     * @mbggenerated Thu Mar 06 10:32:30 CET 2014
     */
    public String getName() {

        return name;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column kom_proj.projectKey
     *
     * @return the value of kom_proj.projectKey
     * @mbggenerated Thu Mar 06 10:32:30 CET 2014
     */
    public String getProjectKey() {

        return projectKey;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column kom_proj.description
     *
     * @param description the value for kom_proj.description
     * @mbggenerated Thu Mar 06 10:32:30 CET 2014
     */
    public void setDescription(final String description) {

        this.description = description;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column kom_proj.icon
     *
     * @param icon the value for kom_proj.icon
     * @mbggenerated Thu Mar 06 10:32:30 CET 2014
     */
    public void setIcon(final String icon) {

        this.icon = icon;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column kom_proj.id
     *
     * @param id the value for kom_proj.id
     * @mbggenerated Thu Mar 06 10:32:30 CET 2014
     */
    public void setId(final Integer id) {

        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column kom_proj.idCustomer
     *
     * @param idCustomer the value for kom_proj.idCustomer
     * @mbggenerated Thu Mar 06 10:32:30 CET 2014
     */
    public void setIdCustomer(final Integer idCustomer) {

        this.idCustomer = idCustomer;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column kom_proj.name
     *
     * @param name the value for kom_proj.name
     * @mbggenerated Thu Mar 06 10:32:30 CET 2014
     */
    public void setName(final String name) {

        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column kom_proj.projectKey
     *
     * @param projectKey the value for kom_proj.projectKey
     * @mbggenerated Thu Mar 06 10:32:30 CET 2014
     */
    public void setProjectKey(final String projectKey) {

        this.projectKey = projectKey;
    }

    public String getAlias() {
        return alias;
    }

    public void setAlias(String alias) {
        this.alias = alias;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table kom_proj
     *
     * @mbggenerated Thu Mar 06 10:32:30 CET 2014
     */
    @Override
    public String toString() {

        final StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", projectKey=").append(projectKey);
        sb.append(", name=").append(name);
        sb.append(", description=").append(description);
        sb.append(", idCustomer=").append(idCustomer);
        sb.append(", icon=").append(icon);
        sb.append(", alias=").append(alias);
        sb.append("]");
        return sb.toString();
    }
}
