package org.komea.product.database.model;

import java.io.Serializable;

import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

public class SuccessFactor implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kom_sfac.id
     *
     * @mbggenerated Thu Mar 06 10:32:30 CET 2014
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kom_sfac.successFactorKey
     *
     * @mbggenerated Thu Mar 06 10:32:30 CET 2014
     */
    @NotNull
    @Size(min = 0, max = 255)
    private String successFactorKey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kom_sfac.name
     *
     * @mbggenerated Thu Mar 06 10:32:30 CET 2014
     */
    @NotNull
    @Size(min = 0, max = 255)
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kom_sfac.description
     *
     * @mbggenerated Thu Mar 06 10:32:30 CET 2014
     */
    @Size(min = 0, max = 2048)
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table kom_sfac
     *
     * @mbggenerated Thu Mar 06 10:32:30 CET 2014
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kom_sfac
     *
     * @mbggenerated Thu Mar 06 10:32:30 CET 2014
     */
    public SuccessFactor(Integer id, String successFactorKey, String name, String description) {
        this.id = id;
        this.successFactorKey = successFactorKey;
        this.name = name;
        this.description = description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kom_sfac
     *
     * @mbggenerated Thu Mar 06 10:32:30 CET 2014
     */
    public SuccessFactor() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kom_sfac.id
     *
     * @return the value of kom_sfac.id
     *
     * @mbggenerated Thu Mar 06 10:32:30 CET 2014
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kom_sfac.id
     *
     * @param id the value for kom_sfac.id
     *
     * @mbggenerated Thu Mar 06 10:32:30 CET 2014
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kom_sfac.successFactorKey
     *
     * @return the value of kom_sfac.successFactorKey
     *
     * @mbggenerated Thu Mar 06 10:32:30 CET 2014
     */
    public String getSuccessFactorKey() {
        return successFactorKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kom_sfac.successFactorKey
     *
     * @param successFactorKey the value for kom_sfac.successFactorKey
     *
     * @mbggenerated Thu Mar 06 10:32:30 CET 2014
     */
    public void setSuccessFactorKey(String successFactorKey) {
        this.successFactorKey = successFactorKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kom_sfac.name
     *
     * @return the value of kom_sfac.name
     *
     * @mbggenerated Thu Mar 06 10:32:30 CET 2014
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kom_sfac.name
     *
     * @param name the value for kom_sfac.name
     *
     * @mbggenerated Thu Mar 06 10:32:30 CET 2014
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kom_sfac.description
     *
     * @return the value of kom_sfac.description
     *
     * @mbggenerated Thu Mar 06 10:32:30 CET 2014
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kom_sfac.description
     *
     * @param description the value for kom_sfac.description
     *
     * @mbggenerated Thu Mar 06 10:32:30 CET 2014
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kom_sfac
     *
     * @mbggenerated Thu Mar 06 10:32:30 CET 2014
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", successFactorKey=").append(successFactorKey);
        sb.append(", name=").append(name);
        sb.append(", description=").append(description);
        sb.append("]");
        return sb.toString();
    }
}