package org.komea.product.eventory.database.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;
import org.komea.product.eventory.database.model.EventMessage;
import org.komea.product.eventory.database.model.EventMessageCriteria;

public interface EventMessageDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kom_evt_storage_blob
     *
     * @mbggenerated Sun Nov 16 11:22:00 CET 2014
     */
    int countByCriteria(EventMessageCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kom_evt_storage_blob
     *
     * @mbggenerated Sun Nov 16 11:22:00 CET 2014
     */
    int deleteByCriteria(EventMessageCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kom_evt_storage_blob
     *
     * @mbggenerated Sun Nov 16 11:22:00 CET 2014
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kom_evt_storage_blob
     *
     * @mbggenerated Sun Nov 16 11:22:00 CET 2014
     */
    int insert(EventMessage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kom_evt_storage_blob
     *
     * @mbggenerated Sun Nov 16 11:22:00 CET 2014
     */
    int insertSelective(EventMessage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kom_evt_storage_blob
     *
     * @mbggenerated Sun Nov 16 11:22:00 CET 2014
     */
    List<EventMessage> selectByCriteriaWithBLOBsWithRowbounds(EventMessageCriteria example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kom_evt_storage_blob
     *
     * @mbggenerated Sun Nov 16 11:22:00 CET 2014
     */
    List<EventMessage> selectByCriteriaWithBLOBs(EventMessageCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kom_evt_storage_blob
     *
     * @mbggenerated Sun Nov 16 11:22:00 CET 2014
     */
    List<EventMessage> selectByCriteriaWithRowbounds(EventMessageCriteria example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kom_evt_storage_blob
     *
     * @mbggenerated Sun Nov 16 11:22:00 CET 2014
     */
    List<EventMessage> selectByCriteria(EventMessageCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kom_evt_storage_blob
     *
     * @mbggenerated Sun Nov 16 11:22:00 CET 2014
     */
    EventMessage selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kom_evt_storage_blob
     *
     * @mbggenerated Sun Nov 16 11:22:00 CET 2014
     */
    int updateByCriteriaSelective(@Param("record") EventMessage record, @Param("example") EventMessageCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kom_evt_storage_blob
     *
     * @mbggenerated Sun Nov 16 11:22:00 CET 2014
     */
    int updateByCriteriaWithBLOBs(@Param("record") EventMessage record, @Param("example") EventMessageCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kom_evt_storage_blob
     *
     * @mbggenerated Sun Nov 16 11:22:00 CET 2014
     */
    int updateByCriteria(@Param("record") EventMessage record, @Param("example") EventMessageCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kom_evt_storage_blob
     *
     * @mbggenerated Sun Nov 16 11:22:00 CET 2014
     */
    int updateByPrimaryKeySelective(EventMessage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kom_evt_storage_blob
     *
     * @mbggenerated Sun Nov 16 11:22:00 CET 2014
     */
    int updateByPrimaryKeyWithBLOBs(EventMessage record);
}