package org.komea.product.eventory.database.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;
import org.komea.product.eventory.database.model.EventAttr;
import org.komea.product.eventory.database.model.EventAttrCriteria;

public interface EventAttrDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kom_evt_storage_attr
     *
     * @mbggenerated Sun Nov 16 11:22:00 CET 2014
     */
    int countByCriteria(EventAttrCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kom_evt_storage_attr
     *
     * @mbggenerated Sun Nov 16 11:22:00 CET 2014
     */
    int deleteByCriteria(EventAttrCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kom_evt_storage_attr
     *
     * @mbggenerated Sun Nov 16 11:22:00 CET 2014
     */
    int insert(EventAttr record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kom_evt_storage_attr
     *
     * @mbggenerated Sun Nov 16 11:22:00 CET 2014
     */
    int insertSelective(EventAttr record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kom_evt_storage_attr
     *
     * @mbggenerated Sun Nov 16 11:22:00 CET 2014
     */
    List<EventAttr> selectByCriteriaWithRowbounds(EventAttrCriteria example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kom_evt_storage_attr
     *
     * @mbggenerated Sun Nov 16 11:22:00 CET 2014
     */
    List<EventAttr> selectByCriteria(EventAttrCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kom_evt_storage_attr
     *
     * @mbggenerated Sun Nov 16 11:22:00 CET 2014
     */
    int updateByCriteriaSelective(@Param("record") EventAttr record, @Param("example") EventAttrCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kom_evt_storage_attr
     *
     * @mbggenerated Sun Nov 16 11:22:00 CET 2014
     */
    int updateByCriteria(@Param("record") EventAttr record, @Param("example") EventAttrCriteria example);
}