package org.komea.product.database.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;
import org.komea.product.database.model.ActivityFilter;
import org.komea.product.database.model.ActivityFilterCriteria;

public interface ActivityFilterDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kom_acfi
     *
     * @mbggenerated Thu Feb 20 01:05:41 CET 2014
     */
    int countByCriteria(ActivityFilterCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kom_acfi
     *
     * @mbggenerated Thu Feb 20 01:05:41 CET 2014
     */
    int deleteByCriteria(ActivityFilterCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kom_acfi
     *
     * @mbggenerated Thu Feb 20 01:05:41 CET 2014
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kom_acfi
     *
     * @mbggenerated Thu Feb 20 01:05:41 CET 2014
     */
    int insert(ActivityFilter record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kom_acfi
     *
     * @mbggenerated Thu Feb 20 01:05:41 CET 2014
     */
    int insertSelective(ActivityFilter record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kom_acfi
     *
     * @mbggenerated Thu Feb 20 01:05:41 CET 2014
     */
    List<ActivityFilter> selectByCriteriaWithRowbounds(ActivityFilterCriteria example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kom_acfi
     *
     * @mbggenerated Thu Feb 20 01:05:41 CET 2014
     */
    List<ActivityFilter> selectByCriteria(ActivityFilterCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kom_acfi
     *
     * @mbggenerated Thu Feb 20 01:05:41 CET 2014
     */
    ActivityFilter selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kom_acfi
     *
     * @mbggenerated Thu Feb 20 01:05:41 CET 2014
     */
    int updateByCriteriaSelective(@Param("record") ActivityFilter record, @Param("example") ActivityFilterCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kom_acfi
     *
     * @mbggenerated Thu Feb 20 01:05:41 CET 2014
     */
    int updateByCriteria(@Param("record") ActivityFilter record, @Param("example") ActivityFilterCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kom_acfi
     *
     * @mbggenerated Thu Feb 20 01:05:41 CET 2014
     */
    int updateByPrimaryKeySelective(ActivityFilter record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kom_acfi
     *
     * @mbggenerated Thu Feb 20 01:05:41 CET 2014
     */
    int updateByPrimaryKey(ActivityFilter record);
}