package org.komea.product.database.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;
import org.komea.product.database.model.HasSuccessFactorKpiCriteria;
import org.komea.product.database.model.HasSuccessFactorKpiKey;

public interface HasSuccessFactorKpiDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kom_has_sfac_kpi
     *
     * @mbggenerated Thu Mar 06 10:32:30 CET 2014
     */
    int countByCriteria(HasSuccessFactorKpiCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kom_has_sfac_kpi
     *
     * @mbggenerated Thu Mar 06 10:32:30 CET 2014
     */
    int deleteByCriteria(HasSuccessFactorKpiCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kom_has_sfac_kpi
     *
     * @mbggenerated Thu Mar 06 10:32:30 CET 2014
     */
    int deleteByPrimaryKey(HasSuccessFactorKpiKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kom_has_sfac_kpi
     *
     * @mbggenerated Thu Mar 06 10:32:30 CET 2014
     */
    int insert(HasSuccessFactorKpiKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kom_has_sfac_kpi
     *
     * @mbggenerated Thu Mar 06 10:32:30 CET 2014
     */
    int insertSelective(HasSuccessFactorKpiKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kom_has_sfac_kpi
     *
     * @mbggenerated Thu Mar 06 10:32:30 CET 2014
     */
    List<HasSuccessFactorKpiKey> selectByCriteriaWithRowbounds(HasSuccessFactorKpiCriteria example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kom_has_sfac_kpi
     *
     * @mbggenerated Thu Mar 06 10:32:30 CET 2014
     */
    List<HasSuccessFactorKpiKey> selectByCriteria(HasSuccessFactorKpiCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kom_has_sfac_kpi
     *
     * @mbggenerated Thu Mar 06 10:32:30 CET 2014
     */
    int updateByCriteriaSelective(@Param("record") HasSuccessFactorKpiKey record, @Param("example") HasSuccessFactorKpiCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kom_has_sfac_kpi
     *
     * @mbggenerated Thu Mar 06 10:32:30 CET 2014
     */
    int updateByCriteria(@Param("record") HasSuccessFactorKpiKey record, @Param("example") HasSuccessFactorKpiCriteria example);
}