/**
 * 
 */

package org.komea.product.database.dao;



import java.io.Serializable;
import java.util.List;

import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;



/**
 * This interface defines the generic DAO methods
 * 
 * @author sleroy
 */
public interface IGenericDAO<TEntity, PK extends Serializable, TCriteria>
{
    
    
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kom_tag
     * 
     * @mbggenerated Fri Feb 14 12:56:55 CET 2014
     */
    int countByCriteria(TCriteria example);
    
    
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kom_tag
     * 
     * @mbggenerated Fri Feb 14 12:56:55 CET 2014
     */
    int deleteByCriteria(TCriteria example);
    
    
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kom_tag
     * 
     * @mbggenerated Fri Feb 14 12:56:55 CET 2014
     */
    int deleteByPrimaryKey(PK id);
    
    
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kom_tag
     * 
     * @mbggenerated Fri Feb 14 12:56:55 CET 2014
     */
    int insert(TEntity record);
    
    
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kom_tag
     * 
     * @mbggenerated Fri Feb 14 12:56:55 CET 2014
     */
    int insertSelective(TEntity record);
    
    
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kom_tag
     * 
     * @mbggenerated Fri Feb 14 12:56:55 CET 2014
     */
    List<TEntity> selectByCriteria(TCriteria example);
    
    
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kom_tag
     * 
     * @mbggenerated Fri Feb 14 12:56:55 CET 2014
     */
    List<TEntity> selectByCriteriaWithRowbounds(TCriteria example, RowBounds rowBounds);
    
    
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kom_tag
     * 
     * @mbggenerated Fri Feb 14 12:56:55 CET 2014
     */
    TEntity selectByPrimaryKey(PK id);
    
    
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kom_tag
     * 
     * @mbggenerated Fri Feb 14 12:56:55 CET 2014
     */
    int updateByCriteria(@Param("record")
    TEntity record, @Param("example")
    TCriteria example);
    
    
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kom_tag
     * 
     * @mbggenerated Fri Feb 14 12:56:55 CET 2014
     */
    int updateByCriteriaSelective(@Param("record")
    TEntity record, @Param("example")
    TCriteria example);
    
    
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kom_tag
     * 
     * @mbggenerated Fri Feb 14 12:56:55 CET 2014
     */
    int updateByPrimaryKey(TEntity record);
    
    
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kom_tag
     * 
     * @mbggenerated Fri Feb 14 12:56:55 CET 2014
     */
    int updateByPrimaryKeySelective(TEntity record);
}
