package org.komea.product.database.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;
import org.komea.product.database.model.Kpi;
import org.komea.product.database.model.KpiCriteria;

public interface KpiDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kom_kpi
     *
     * @mbggenerated Tue Feb 11 16:06:30 CET 2014
     */
    int countByCriteria(KpiCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kom_kpi
     *
     * @mbggenerated Tue Feb 11 16:06:30 CET 2014
     */
    int deleteByCriteria(KpiCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kom_kpi
     *
     * @mbggenerated Tue Feb 11 16:06:30 CET 2014
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kom_kpi
     *
     * @mbggenerated Tue Feb 11 16:06:30 CET 2014
     */
    int insert(Kpi record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kom_kpi
     *
     * @mbggenerated Tue Feb 11 16:06:30 CET 2014
     */
    int insertSelective(Kpi record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kom_kpi
     *
     * @mbggenerated Tue Feb 11 16:06:30 CET 2014
     */
    List<Kpi> selectByExampleWithBLOBsWithRowbounds(KpiCriteria example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kom_kpi
     *
     * @mbggenerated Tue Feb 11 16:06:30 CET 2014
     */
    List<Kpi> selectByExampleWithBLOBs(KpiCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kom_kpi
     *
     * @mbggenerated Tue Feb 11 16:06:30 CET 2014
     */
    List<Kpi> selectByCriteriaWithRowbounds(KpiCriteria example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kom_kpi
     *
     * @mbggenerated Tue Feb 11 16:06:30 CET 2014
     */
    List<Kpi> selectByCriteria(KpiCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kom_kpi
     *
     * @mbggenerated Tue Feb 11 16:06:30 CET 2014
     */
    Kpi selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kom_kpi
     *
     * @mbggenerated Tue Feb 11 16:06:30 CET 2014
     */
    int updateByCriteriaSelective(@Param("record") Kpi record, @Param("example") KpiCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kom_kpi
     *
     * @mbggenerated Tue Feb 11 16:06:30 CET 2014
     */
    int updateByExampleWithBLOBs(@Param("record") Kpi record, @Param("example") KpiCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kom_kpi
     *
     * @mbggenerated Tue Feb 11 16:06:30 CET 2014
     */
    int updateByCriteria(@Param("record") Kpi record, @Param("example") KpiCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kom_kpi
     *
     * @mbggenerated Tue Feb 11 16:06:30 CET 2014
     */
    int updateByPrimaryKeySelective(Kpi record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kom_kpi
     *
     * @mbggenerated Tue Feb 11 16:06:30 CET 2014
     */
    int updateByPrimaryKeyWithBLOBs(Kpi record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kom_kpi
     *
     * @mbggenerated Tue Feb 11 16:06:30 CET 2014
     */
    int updateByPrimaryKey(Kpi record);
}