
package org.komea.product.database.dao;



import java.util.List;

import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;
import org.komea.product.database.model.Kpi;
import org.komea.product.database.model.KpiCriteria;



public interface KpiDao extends IGenericDAO<Kpi, Integer, KpiCriteria>
{
    
    
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kom_kpi
     * 
     * @mbggenerated Mon May 12 15:10:09 CEST 2014
     */
    @Override
    int countByCriteria(KpiCriteria example);
    
    
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kom_kpi
     * 
     * @mbggenerated Mon May 12 15:10:09 CEST 2014
     */
    @Override
    int deleteByCriteria(KpiCriteria example);
    
    
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kom_kpi
     * 
     * @mbggenerated Mon May 12 15:10:09 CEST 2014
     */
    @Override
    int deleteByPrimaryKey(Integer id);
    
    
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kom_kpi
     * 
     * @mbggenerated Mon May 12 15:10:09 CEST 2014
     */
    @Override
    int insert(Kpi record);
    
    
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kom_kpi
     * 
     * @mbggenerated Mon May 12 15:10:09 CEST 2014
     */
    @Override
    int insertSelective(Kpi record);
    
    
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kom_kpi
     * 
     * @mbggenerated Mon May 12 15:10:09 CEST 2014
     */
    @Override
    List<Kpi> selectByCriteria(KpiCriteria example);
    
    
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kom_kpi
     * 
     * @mbggenerated Mon May 12 15:10:09 CEST 2014
     */
    List<Kpi> selectByCriteriaWithBLOBs(KpiCriteria example);
    
    
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kom_kpi
     * 
     * @mbggenerated Mon May 12 15:10:09 CEST 2014
     */
    List<Kpi> selectByCriteriaWithBLOBsWithRowbounds(KpiCriteria example, RowBounds rowBounds);
    
    
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kom_kpi
     * 
     * @mbggenerated Mon May 12 15:10:09 CEST 2014
     */
    @Override
    List<Kpi> selectByCriteriaWithRowbounds(KpiCriteria example, RowBounds rowBounds);
    
    
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kom_kpi
     * 
     * @mbggenerated Mon May 12 15:10:09 CEST 2014
     */
    @Override
    Kpi selectByPrimaryKey(Integer id);
    
    
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kom_kpi
     * 
     * @mbggenerated Mon May 12 15:10:09 CEST 2014
     */
    @Override
    int updateByCriteria(@Param("record")
    Kpi record, @Param("example")
    KpiCriteria example);
    
    
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kom_kpi
     * 
     * @mbggenerated Mon May 12 15:10:09 CEST 2014
     */
    @Override
    int updateByCriteriaSelective(@Param("record")
    Kpi record, @Param("example")
    KpiCriteria example);
    
    
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kom_kpi
     * 
     * @mbggenerated Mon May 12 15:10:09 CEST 2014
     */
    int updateByCriteriaWithBLOBs(@Param("record")
    Kpi record, @Param("example")
    KpiCriteria example);
    
    
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kom_kpi
     * 
     * @mbggenerated Mon May 12 15:10:09 CEST 2014
     */
    @Override
    int updateByPrimaryKey(Kpi record);
    
    
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kom_kpi
     * 
     * @mbggenerated Mon May 12 15:10:09 CEST 2014
     */
    @Override
    int updateByPrimaryKeySelective(Kpi record);
    
    
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kom_kpi
     * 
     * @mbggenerated Mon May 12 15:10:09 CEST 2014
     */
    int updateByPrimaryKeyWithBLOBs(Kpi record);
}
