
package org.komea.product.database.dao;



import java.util.List;

import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;
import org.komea.product.database.model.Kpi;
import org.komea.product.database.model.KpiCriteria;



public interface KpiDao extends IGenericDAO<Kpi, Integer, KpiCriteria>
{
    
    
    // /
    
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kom_kpi
     * 
     * @mbggenerated Wed Feb 19 11:03:52 CET 2014
     */
    List<Kpi> selectByCriteriaWithBLOBs(KpiCriteria example);
    
    
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kom_kpi
     * 
     * @mbggenerated Wed Feb 19 11:03:52 CET 2014
     */
    List<Kpi> selectByCriteriaWithBLOBsWithRowbounds(KpiCriteria example, RowBounds rowBounds);
    
    
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kom_kpi
     * 
     * @mbggenerated Wed Feb 19 11:03:52 CET 2014
     */
    int updateByCriteriaWithBLOBs(@Param("record")
    Kpi record, @Param("example")
    KpiCriteria example);
}
