
package org.komea.product.database.dao;



import java.util.List;

import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;
import org.komea.product.database.model.KpiGoal;
import org.komea.product.database.model.KpiGoalCriteria;



public interface KpiGoalDao extends IGenericDAO<KpiGoal, Integer, KpiGoalCriteria>
{
    
    
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kom_kpigoal
     * 
     * @mbggenerated Mon May 26 14:58:02 CEST 2014
     */
    @Override
    int countByCriteria(KpiGoalCriteria example);
    
    
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kom_kpigoal
     * 
     * @mbggenerated Mon May 26 14:58:02 CEST 2014
     */
    @Override
    int deleteByCriteria(KpiGoalCriteria example);
    
    
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kom_kpigoal
     * 
     * @mbggenerated Mon May 26 14:58:02 CEST 2014
     */
    @Override
    int deleteByPrimaryKey(Integer id);
    
    
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kom_kpigoal
     * 
     * @mbggenerated Mon May 26 14:58:02 CEST 2014
     */
    @Override
    int insert(KpiGoal record);
    
    
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kom_kpigoal
     * 
     * @mbggenerated Mon May 26 14:58:02 CEST 2014
     */
    @Override
    int insertSelective(KpiGoal record);
    
    
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kom_kpigoal
     * 
     * @mbggenerated Mon May 26 14:58:02 CEST 2014
     */
    @Override
    List<KpiGoal> selectByCriteria(KpiGoalCriteria example);
    
    
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kom_kpigoal
     * 
     * @mbggenerated Mon May 26 14:58:02 CEST 2014
     */
    @Override
    List<KpiGoal> selectByCriteriaWithRowbounds(KpiGoalCriteria example, RowBounds rowBounds);
    
    
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kom_kpigoal
     * 
     * @mbggenerated Mon May 26 14:58:02 CEST 2014
     */
    @Override
    KpiGoal selectByPrimaryKey(Integer id);
    
    
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kom_kpigoal
     * 
     * @mbggenerated Mon May 26 14:58:02 CEST 2014
     */
    @Override
    int updateByCriteria(@Param("record")
    KpiGoal record, @Param("example")
    KpiGoalCriteria example);
    
    
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kom_kpigoal
     * 
     * @mbggenerated Mon May 26 14:58:02 CEST 2014
     */
    @Override
    int updateByCriteriaSelective(@Param("record")
    KpiGoal record, @Param("example")
    KpiGoalCriteria example);
    
    
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kom_kpigoal
     * 
     * @mbggenerated Mon May 26 14:58:02 CEST 2014
     */
    @Override
    int updateByPrimaryKey(KpiGoal record);
    
    
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kom_kpigoal
     * 
     * @mbggenerated Mon May 26 14:58:02 CEST 2014
     */
    @Override
    int updateByPrimaryKeySelective(KpiGoal record);
}
