package org.komea.product.database.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;
import org.komea.product.database.model.Link;
import org.komea.product.database.model.LinkCriteria;

public interface LinkDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kom_link
     *
     * @mbggenerated Wed Feb 19 11:03:52 CET 2014
     */
    int countByCriteria(LinkCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kom_link
     *
     * @mbggenerated Wed Feb 19 11:03:52 CET 2014
     */
    int deleteByCriteria(LinkCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kom_link
     *
     * @mbggenerated Wed Feb 19 11:03:52 CET 2014
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kom_link
     *
     * @mbggenerated Wed Feb 19 11:03:52 CET 2014
     */
    int insert(Link record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kom_link
     *
     * @mbggenerated Wed Feb 19 11:03:52 CET 2014
     */
    int insertSelective(Link record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kom_link
     *
     * @mbggenerated Wed Feb 19 11:03:52 CET 2014
     */
    List<Link> selectByCriteriaWithRowbounds(LinkCriteria example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kom_link
     *
     * @mbggenerated Wed Feb 19 11:03:52 CET 2014
     */
    List<Link> selectByCriteria(LinkCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kom_link
     *
     * @mbggenerated Wed Feb 19 11:03:52 CET 2014
     */
    Link selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kom_link
     *
     * @mbggenerated Wed Feb 19 11:03:52 CET 2014
     */
    int updateByCriteriaSelective(@Param("record") Link record, @Param("example") LinkCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kom_link
     *
     * @mbggenerated Wed Feb 19 11:03:52 CET 2014
     */
    int updateByCriteria(@Param("record") Link record, @Param("example") LinkCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kom_link
     *
     * @mbggenerated Wed Feb 19 11:03:52 CET 2014
     */
    int updateByPrimaryKeySelective(Link record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kom_link
     *
     * @mbggenerated Wed Feb 19 11:03:52 CET 2014
     */
    int updateByPrimaryKey(Link record);
}