
package org.komea.product.database.dao;



import java.util.List;

import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;
import org.komea.product.database.model.Measure;
import org.komea.product.database.model.MeasureCriteria;
import org.komea.product.model.timeserie.EntityIdValue;
import org.komea.product.model.timeserie.PeriodTimeSerieOptions;
import org.komea.product.model.timeserie.TimeCoordinate;
import org.komea.product.model.timeserie.TimeSerieOptions;
import org.komea.product.service.dto.EntityKey;



public interface MeasureDao
{
    
    
    /**
     * This method builds a time serie from the history given a list of options.
     * Basically the purpose of a time serie is to build charts. A time serie is
     * either global to the type of entities of a kpi or for a given entity (1
     * or all).
     * 
     * @return a time serie object
     * @param _timeSerieOptions
     *            the time serie options.
     * @return the coordinates of the time serie
     */
    List<TimeCoordinate> buildGlobalPeriodTimeSeries(@Param("options")
    PeriodTimeSerieOptions _timeSerieOptions);
    
    
    /**
     * Builsd period time and series
     * 
     * @param _timeSerieOptions
     *            the time serie options.
     * @return the coordinates
     */
    List<TimeCoordinate> buildPeriodTimeSeries(@Param("options")
    PeriodTimeSerieOptions _timeSerieOptions, @Param("key")
    EntityKey _entityKey);
    
    
    /**
     * Builds period time and series
     * 
     * @param _timeSerieOptions
     *            the time serie options.
     * @return the coordinates
     */
    List<TimeCoordinate> buildTimeSeries(@Param("options")
    TimeSerieOptions _timeSerieOptions, @Param("key")
    EntityKey _entityKey);
    
    
    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table kom_msr
     * 
     * @mbggenerated Sat May 10 14:47:35 CEST 2014
     */
    int countByCriteria(MeasureCriteria example);
    
    
    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table kom_msr
     * 
     * @mbggenerated Sat May 10 14:47:35 CEST 2014
     */
    int deleteByCriteria(MeasureCriteria example);
    
    
    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table kom_msr
     * 
     * @mbggenerated Sat May 10 14:47:35 CEST 2014
     */
    int deleteByPrimaryKey(Integer id);
    
    
    /**
     * @param _options
     * @param _entityKey
     * @return
     */
    Double evaluateKpiValue(@Param("options")
    TimeSerieOptions _options, @Param("key")
    EntityKey _entityKey);
    
    
    /**
     * @param _options
     * @param _entityKey
     * @return
     */
    Double evaluateKpiValueOnPeriod(@Param("options")
    PeriodTimeSerieOptions _options, @Param("key")
    EntityKey _entityKey);
    
    
    /**
     * Returns the kp ivalues according the time serie options.
     * 
     * @param _options
     * @return
     */
    
    List<EntityIdValue> evaluateKpiValues(@Param("options")
    TimeSerieOptions _options);
    
    
    /**
     * @param _options
     * @return
     */
    List<EntityIdValue> evaluateKpiValuesOnPeriod(@Param("options")
    PeriodTimeSerieOptions _options);
    
    
    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table kom_msr
     * 
     * @mbggenerated Sat May 10 14:47:35 CEST 2014
     */
    int insert(Measure record);
    
    
    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table kom_msr
     * 
     * @mbggenerated Sat May 10 14:47:35 CEST 2014
     */
    int insertSelective(Measure record);
    
    
    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table kom_msr
     * 
     * @mbggenerated Sat May 10 14:47:35 CEST 2014
     */
    List<Measure> selectByCriteria(MeasureCriteria example);
    
    
    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table kom_msr
     * 
     * @mbggenerated Sat May 10 14:47:35 CEST 2014
     */
    List<Measure> selectByCriteriaWithRowbounds(MeasureCriteria example, RowBounds rowBounds);
    
    
    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table kom_msr
     * 
     * @mbggenerated Sat May 10 14:47:35 CEST 2014
     */
    Measure selectByPrimaryKey(Integer id);
    
    
    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table kom_msr
     * 
     * @mbggenerated Sat May 10 14:47:35 CEST 2014
     */
    int updateByCriteria(@Param("record")
    Measure record, @Param("example")
    MeasureCriteria example);
    
    
    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table kom_msr
     * 
     * @mbggenerated Sat May 10 14:47:35 CEST 2014
     */
    int updateByCriteriaSelective(@Param("record")
    Measure record, @Param("example")
    MeasureCriteria example);
    
    
    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table kom_msr
     * 
     * @mbggenerated Sat May 10 14:47:35 CEST 2014
     */
    int updateByPrimaryKey(Measure record);
    
    
    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table kom_msr
     * 
     * @mbggenerated Sat May 10 14:47:35 CEST 2014
     */
    int updateByPrimaryKeySelective(Measure record);
    
}
