
package org.komea.product.database.dao;



import java.util.List;

import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;
import org.komea.product.database.model.Measure;
import org.komea.product.database.model.MeasureCriteria;



public interface MeasureDao extends IGenericDAO<Measure, Integer, MeasureCriteria>
{
    
    
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kom_msr
     * 
     * @mbggenerated Thu May 08 13:09:26 CEST 2014
     */
    int countByCriteria(MeasureCriteria example);
    
    
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kom_msr
     * 
     * @mbggenerated Thu May 08 13:09:26 CEST 2014
     */
    int deleteByCriteria(MeasureCriteria example);
    
    
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kom_msr
     * 
     * @mbggenerated Thu May 08 13:09:26 CEST 2014
     */
    int deleteByPrimaryKey(Integer id);
    
    
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kom_msr
     * 
     * @mbggenerated Thu May 08 13:09:26 CEST 2014
     */
    int insert(Measure record);
    
    
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kom_msr
     * 
     * @mbggenerated Thu May 08 13:09:26 CEST 2014
     */
    int insertSelective(Measure record);
    
    
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kom_msr
     * 
     * @mbggenerated Thu May 08 13:09:26 CEST 2014
     */
    List<Measure> selectByCriteria(MeasureCriteria example);
    
    
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kom_msr
     * 
     * @mbggenerated Thu May 08 13:09:26 CEST 2014
     */
    List<Measure> selectByCriteriaWithRowbounds(MeasureCriteria example, RowBounds rowBounds);
    
    
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kom_msr
     * 
     * @mbggenerated Thu May 08 13:09:26 CEST 2014
     */
    Measure selectByPrimaryKey(Integer id);
    
    
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kom_msr
     * 
     * @mbggenerated Thu May 08 13:09:26 CEST 2014
     */
    int updateByCriteria(@Param("record")
    Measure record, @Param("example")
    MeasureCriteria example);
    
    
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kom_msr
     * 
     * @mbggenerated Thu May 08 13:09:26 CEST 2014
     */
    int updateByCriteriaSelective(@Param("record")
    Measure record, @Param("example")
    MeasureCriteria example);
    
    
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kom_msr
     * 
     * @mbggenerated Thu May 08 13:09:26 CEST 2014
     */
    int updateByPrimaryKey(Measure record);
    
    
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kom_msr
     * 
     * @mbggenerated Thu May 08 13:09:26 CEST 2014
     */
    int updateByPrimaryKeySelective(Measure record);
}
