package org.komea.product.database.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;
import org.komea.product.database.model.PersonRole;
import org.komea.product.database.model.PersonRoleCriteria;

public interface PersonRoleDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kom_pero
     *
     * @mbggenerated Wed Feb 19 11:03:52 CET 2014
     */
    int countByCriteria(PersonRoleCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kom_pero
     *
     * @mbggenerated Wed Feb 19 11:03:52 CET 2014
     */
    int deleteByCriteria(PersonRoleCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kom_pero
     *
     * @mbggenerated Wed Feb 19 11:03:52 CET 2014
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kom_pero
     *
     * @mbggenerated Wed Feb 19 11:03:52 CET 2014
     */
    int insert(PersonRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kom_pero
     *
     * @mbggenerated Wed Feb 19 11:03:52 CET 2014
     */
    int insertSelective(PersonRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kom_pero
     *
     * @mbggenerated Wed Feb 19 11:03:52 CET 2014
     */
    List<PersonRole> selectByCriteriaWithRowbounds(PersonRoleCriteria example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kom_pero
     *
     * @mbggenerated Wed Feb 19 11:03:52 CET 2014
     */
    List<PersonRole> selectByCriteria(PersonRoleCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kom_pero
     *
     * @mbggenerated Wed Feb 19 11:03:52 CET 2014
     */
    PersonRole selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kom_pero
     *
     * @mbggenerated Wed Feb 19 11:03:52 CET 2014
     */
    int updateByCriteriaSelective(@Param("record") PersonRole record, @Param("example") PersonRoleCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kom_pero
     *
     * @mbggenerated Wed Feb 19 11:03:52 CET 2014
     */
    int updateByCriteria(@Param("record") PersonRole record, @Param("example") PersonRoleCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kom_pero
     *
     * @mbggenerated Wed Feb 19 11:03:52 CET 2014
     */
    int updateByPrimaryKeySelective(PersonRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kom_pero
     *
     * @mbggenerated Wed Feb 19 11:03:52 CET 2014
     */
    int updateByPrimaryKey(PersonRole record);
}