package org.komea.product.database.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;
import org.komea.product.database.model.PersonGroup;
import org.komea.product.database.model.PersonGroupCriteria;

public interface PersonGroupDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kom_pegr
     *
     * @mbggenerated Tue Feb 11 15:56:49 CET 2014
     */
    int countByCriteria(PersonGroupCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kom_pegr
     *
     * @mbggenerated Tue Feb 11 15:56:49 CET 2014
     */
    int deleteByCriteria(PersonGroupCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kom_pegr
     *
     * @mbggenerated Tue Feb 11 15:56:49 CET 2014
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kom_pegr
     *
     * @mbggenerated Tue Feb 11 15:56:49 CET 2014
     */
    int insert(PersonGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kom_pegr
     *
     * @mbggenerated Tue Feb 11 15:56:49 CET 2014
     */
    int insertSelective(PersonGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kom_pegr
     *
     * @mbggenerated Tue Feb 11 15:56:49 CET 2014
     */
    List<PersonGroup> selectByCriteriaWithRowbounds(PersonGroupCriteria example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kom_pegr
     *
     * @mbggenerated Tue Feb 11 15:56:49 CET 2014
     */
    List<PersonGroup> selectByCriteria(PersonGroupCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kom_pegr
     *
     * @mbggenerated Tue Feb 11 15:56:49 CET 2014
     */
    PersonGroup selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kom_pegr
     *
     * @mbggenerated Tue Feb 11 15:56:49 CET 2014
     */
    int updateByCriteriaSelective(@Param("record") PersonGroup record, @Param("example") PersonGroupCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kom_pegr
     *
     * @mbggenerated Tue Feb 11 15:56:49 CET 2014
     */
    int updateByCriteria(@Param("record") PersonGroup record, @Param("example") PersonGroupCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kom_pegr
     *
     * @mbggenerated Tue Feb 11 15:56:49 CET 2014
     */
    int updateByPrimaryKeySelective(PersonGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kom_pegr
     *
     * @mbggenerated Tue Feb 11 15:56:49 CET 2014
     */
    int updateByPrimaryKey(PersonGroup record);
}