package org.komea.product.database.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.komea.product.database.model.ProviderSetting;
import org.komea.product.database.model.ProviderSettingCriteria;

public interface ProviderSettingDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kom_pvds
     *
     * @mbggenerated Wed Feb 05 10:10:36 CET 2014
     */
    int countByCriteria(ProviderSettingCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kom_pvds
     *
     * @mbggenerated Wed Feb 05 10:10:36 CET 2014
     */
    int deleteByCriteria(ProviderSettingCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kom_pvds
     *
     * @mbggenerated Wed Feb 05 10:10:36 CET 2014
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kom_pvds
     *
     * @mbggenerated Wed Feb 05 10:10:36 CET 2014
     */
    int insert(ProviderSetting record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kom_pvds
     *
     * @mbggenerated Wed Feb 05 10:10:36 CET 2014
     */
    int insertSelective(ProviderSetting record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kom_pvds
     *
     * @mbggenerated Wed Feb 05 10:10:36 CET 2014
     */
    List<ProviderSetting> selectByCriteria(ProviderSettingCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kom_pvds
     *
     * @mbggenerated Wed Feb 05 10:10:36 CET 2014
     */
    ProviderSetting selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kom_pvds
     *
     * @mbggenerated Wed Feb 05 10:10:36 CET 2014
     */
    int updateByCriteriaSelective(@Param("record") ProviderSetting record, @Param("example") ProviderSettingCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kom_pvds
     *
     * @mbggenerated Wed Feb 05 10:10:36 CET 2014
     */
    int updateByCriteria(@Param("record") ProviderSetting record, @Param("example") ProviderSettingCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kom_pvds
     *
     * @mbggenerated Wed Feb 05 10:10:36 CET 2014
     */
    int updateByPrimaryKeySelective(ProviderSetting record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kom_pvds
     *
     * @mbggenerated Wed Feb 05 10:10:36 CET 2014
     */
    int updateByPrimaryKey(ProviderSetting record);
}