package org.komea.product.database.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;
import org.komea.product.database.model.Setting;
import org.komea.product.database.model.SettingCriteria;

public interface SettingDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kom_setting
     *
     * @mbggenerated Tue Feb 11 15:56:49 CET 2014
     */
    int countByCriteria(SettingCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kom_setting
     *
     * @mbggenerated Tue Feb 11 15:56:49 CET 2014
     */
    int deleteByCriteria(SettingCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kom_setting
     *
     * @mbggenerated Tue Feb 11 15:56:49 CET 2014
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kom_setting
     *
     * @mbggenerated Tue Feb 11 15:56:49 CET 2014
     */
    int insert(Setting record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kom_setting
     *
     * @mbggenerated Tue Feb 11 15:56:49 CET 2014
     */
    int insertSelective(Setting record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kom_setting
     *
     * @mbggenerated Tue Feb 11 15:56:49 CET 2014
     */
    List<Setting> selectByCriteriaWithRowbounds(SettingCriteria example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kom_setting
     *
     * @mbggenerated Tue Feb 11 15:56:49 CET 2014
     */
    List<Setting> selectByCriteria(SettingCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kom_setting
     *
     * @mbggenerated Tue Feb 11 15:56:49 CET 2014
     */
    Setting selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kom_setting
     *
     * @mbggenerated Tue Feb 11 15:56:49 CET 2014
     */
    int updateByCriteriaSelective(@Param("record") Setting record, @Param("example") SettingCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kom_setting
     *
     * @mbggenerated Tue Feb 11 15:56:49 CET 2014
     */
    int updateByCriteria(@Param("record") Setting record, @Param("example") SettingCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kom_setting
     *
     * @mbggenerated Tue Feb 11 15:56:49 CET 2014
     */
    int updateByPrimaryKeySelective(Setting record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kom_setting
     *
     * @mbggenerated Tue Feb 11 15:56:49 CET 2014
     */
    int updateByPrimaryKey(Setting record);
}