package org.komea.product.database.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;
import org.komea.product.database.model.Tag;
import org.komea.product.database.model.TagCriteria;

public interface TagDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kom_tag
     *
     * @mbggenerated Thu Feb 20 01:05:41 CET 2014
     */
    int countByCriteria(TagCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kom_tag
     *
     * @mbggenerated Thu Feb 20 01:05:41 CET 2014
     */
    int deleteByCriteria(TagCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kom_tag
     *
     * @mbggenerated Thu Feb 20 01:05:41 CET 2014
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kom_tag
     *
     * @mbggenerated Thu Feb 20 01:05:41 CET 2014
     */
    int insert(Tag record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kom_tag
     *
     * @mbggenerated Thu Feb 20 01:05:41 CET 2014
     */
    int insertSelective(Tag record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kom_tag
     *
     * @mbggenerated Thu Feb 20 01:05:41 CET 2014
     */
    List<Tag> selectByCriteriaWithRowbounds(TagCriteria example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kom_tag
     *
     * @mbggenerated Thu Feb 20 01:05:41 CET 2014
     */
    List<Tag> selectByCriteria(TagCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kom_tag
     *
     * @mbggenerated Thu Feb 20 01:05:41 CET 2014
     */
    Tag selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kom_tag
     *
     * @mbggenerated Thu Feb 20 01:05:41 CET 2014
     */
    int updateByCriteriaSelective(@Param("record") Tag record, @Param("example") TagCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kom_tag
     *
     * @mbggenerated Thu Feb 20 01:05:41 CET 2014
     */
    int updateByCriteria(@Param("record") Tag record, @Param("example") TagCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kom_tag
     *
     * @mbggenerated Thu Feb 20 01:05:41 CET 2014
     */
    int updateByPrimaryKeySelective(Tag record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kom_tag
     *
     * @mbggenerated Thu Feb 20 01:05:41 CET 2014
     */
    int updateByPrimaryKey(Tag record);
}