package org.komea.product.database.model;

import java.io.Serializable;

public class GroupKind implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kom_grk.id
     *
     * @mbggenerated Mon Jan 13 16:47:17 CET 2014
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kom_grk.name
     *
     * @mbggenerated Mon Jan 13 16:47:17 CET 2014
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table kom_grk
     *
     * @mbggenerated Mon Jan 13 16:47:17 CET 2014
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kom_grk
     *
     * @mbggenerated Mon Jan 13 16:47:17 CET 2014
     */
    public GroupKind(Integer id, String name) {
        this.id = id;
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kom_grk
     *
     * @mbggenerated Mon Jan 13 16:47:17 CET 2014
     */
    public GroupKind() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kom_grk.id
     *
     * @return the value of kom_grk.id
     *
     * @mbggenerated Mon Jan 13 16:47:17 CET 2014
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kom_grk.id
     *
     * @param id the value for kom_grk.id
     *
     * @mbggenerated Mon Jan 13 16:47:17 CET 2014
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kom_grk.name
     *
     * @return the value of kom_grk.name
     *
     * @mbggenerated Mon Jan 13 16:47:17 CET 2014
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kom_grk.name
     *
     * @param name the value for kom_grk.name
     *
     * @mbggenerated Mon Jan 13 16:47:17 CET 2014
     */
    public void setName(String name) {
        this.name = name;
    }
}