package org.komea.product.plugins.bugzilla.sah.model;

public enum BugStatus {

    NEW, UNCONFIRMED, ONHOLD, ACCEPTED, ASSIGNED, OPENED,
    READY_FOR_COMPONENT, READY_TO_INTEGRATE, MERGED, INTEGRATED,
    RESOLVED,
    DELIVERED, CLOSED,
    REOPENED,
    POSTPONED, STANDBY,
    READY_TO_MERGE,
    COMPONENT_RELEASED, CONFIG_UPDATED
}
