package org.komea.product.database.model;

public class HasPersonKpiAlertTypeKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kom_has_kpia_pe.idKpiAlertType
     *
     * @mbggenerated Wed Jan 08 18:58:18 CET 2014
     */
    private Integer idKpiAlertType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kom_has_kpia_pe.idPerson
     *
     * @mbggenerated Wed Jan 08 18:58:18 CET 2014
     */
    private Integer idPerson;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kom_has_kpia_pe.idKpiAlertType
     *
     * @return the value of kom_has_kpia_pe.idKpiAlertType
     *
     * @mbggenerated Wed Jan 08 18:58:18 CET 2014
     */
    public Integer getIdKpiAlertType() {
        return idKpiAlertType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kom_has_kpia_pe.idKpiAlertType
     *
     * @param idKpiAlertType the value for kom_has_kpia_pe.idKpiAlertType
     *
     * @mbggenerated Wed Jan 08 18:58:18 CET 2014
     */
    public void setIdKpiAlertType(Integer idKpiAlertType) {
        this.idKpiAlertType = idKpiAlertType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kom_has_kpia_pe.idPerson
     *
     * @return the value of kom_has_kpia_pe.idPerson
     *
     * @mbggenerated Wed Jan 08 18:58:18 CET 2014
     */
    public Integer getIdPerson() {
        return idPerson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kom_has_kpia_pe.idPerson
     *
     * @param idPerson the value for kom_has_kpia_pe.idPerson
     *
     * @mbggenerated Wed Jan 08 18:58:18 CET 2014
     */
    public void setIdPerson(Integer idPerson) {
        this.idPerson = idPerson;
    }
}