package org.komea.product.database.model;

public class HasProjectTagKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kom_has_proj_tag.idProject
     *
     * @mbggenerated Wed Jan 08 17:24:48 CET 2014
     */
    private Integer idProject;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kom_has_proj_tag.idTag
     *
     * @mbggenerated Wed Jan 08 17:24:48 CET 2014
     */
    private Integer idTag;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kom_has_proj_tag.idProject
     *
     * @return the value of kom_has_proj_tag.idProject
     *
     * @mbggenerated Wed Jan 08 17:24:48 CET 2014
     */
    public Integer getIdProject() {
        return idProject;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kom_has_proj_tag.idProject
     *
     * @param idProject the value for kom_has_proj_tag.idProject
     *
     * @mbggenerated Wed Jan 08 17:24:48 CET 2014
     */
    public void setIdProject(Integer idProject) {
        this.idProject = idProject;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kom_has_proj_tag.idTag
     *
     * @return the value of kom_has_proj_tag.idTag
     *
     * @mbggenerated Wed Jan 08 17:24:48 CET 2014
     */
    public Integer getIdTag() {
        return idTag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kom_has_proj_tag.idTag
     *
     * @param idTag the value for kom_has_proj_tag.idTag
     *
     * @mbggenerated Wed Jan 08 17:24:48 CET 2014
     */
    public void setIdTag(Integer idTag) {
        this.idTag = idTag;
    }
}