package org.komea.product.database.model;

import java.io.Serializable;
import java.util.Date;

public class KpiAlertType implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kom_kpia.idKpiAlertType
     *
     * @mbggenerated Thu Jan 09 18:27:42 CET 2014
     */
    private Integer idKpiAlertType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kom_kpia.idKpi
     *
     * @mbggenerated Thu Jan 09 18:27:42 CET 2014
     */
    private Integer idKpi;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kom_kpia.key
     *
     * @mbggenerated Thu Jan 09 18:27:42 CET 2014
     */
    private String key;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kom_kpia.name
     *
     * @mbggenerated Thu Jan 09 18:27:42 CET 2014
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kom_kpia.severity
     *
     * @mbggenerated Thu Jan 09 18:27:42 CET 2014
     */
    private Integer severity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kom_kpia.value
     *
     * @mbggenerated Thu Jan 09 18:27:42 CET 2014
     */
    private Double value;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kom_kpia.averageSince
     *
     * @mbggenerated Thu Jan 09 18:27:42 CET 2014
     */
    private Date averageSince;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kom_kpia.operator
     *
     * @mbggenerated Thu Jan 09 18:27:42 CET 2014
     */
    private Integer operator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kom_kpia.enabled
     *
     * @mbggenerated Thu Jan 09 18:27:42 CET 2014
     */
    private Boolean enabled;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kom_kpia.description
     *
     * @mbggenerated Thu Jan 09 18:27:42 CET 2014
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table kom_kpia
     *
     * @mbggenerated Thu Jan 09 18:27:42 CET 2014
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kom_kpia
     *
     * @mbggenerated Thu Jan 09 18:27:42 CET 2014
     */
    public KpiAlertType(Integer idKpiAlertType, Integer idKpi, String key, String name, Integer severity, Double value, Date averageSince, Integer operator, Boolean enabled, String description) {
        this.idKpiAlertType = idKpiAlertType;
        this.idKpi = idKpi;
        this.key = key;
        this.name = name;
        this.severity = severity;
        this.value = value;
        this.averageSince = averageSince;
        this.operator = operator;
        this.enabled = enabled;
        this.description = description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kom_kpia
     *
     * @mbggenerated Thu Jan 09 18:27:42 CET 2014
     */
    public KpiAlertType() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kom_kpia.idKpiAlertType
     *
     * @return the value of kom_kpia.idKpiAlertType
     *
     * @mbggenerated Thu Jan 09 18:27:42 CET 2014
     */
    public Integer getIdKpiAlertType() {
        return idKpiAlertType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kom_kpia.idKpiAlertType
     *
     * @param idKpiAlertType the value for kom_kpia.idKpiAlertType
     *
     * @mbggenerated Thu Jan 09 18:27:42 CET 2014
     */
    public void setIdKpiAlertType(Integer idKpiAlertType) {
        this.idKpiAlertType = idKpiAlertType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kom_kpia.idKpi
     *
     * @return the value of kom_kpia.idKpi
     *
     * @mbggenerated Thu Jan 09 18:27:42 CET 2014
     */
    public Integer getIdKpi() {
        return idKpi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kom_kpia.idKpi
     *
     * @param idKpi the value for kom_kpia.idKpi
     *
     * @mbggenerated Thu Jan 09 18:27:42 CET 2014
     */
    public void setIdKpi(Integer idKpi) {
        this.idKpi = idKpi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kom_kpia.key
     *
     * @return the value of kom_kpia.key
     *
     * @mbggenerated Thu Jan 09 18:27:42 CET 2014
     */
    public String getKey() {
        return key;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kom_kpia.key
     *
     * @param key the value for kom_kpia.key
     *
     * @mbggenerated Thu Jan 09 18:27:42 CET 2014
     */
    public void setKey(String key) {
        this.key = key;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kom_kpia.name
     *
     * @return the value of kom_kpia.name
     *
     * @mbggenerated Thu Jan 09 18:27:42 CET 2014
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kom_kpia.name
     *
     * @param name the value for kom_kpia.name
     *
     * @mbggenerated Thu Jan 09 18:27:42 CET 2014
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kom_kpia.severity
     *
     * @return the value of kom_kpia.severity
     *
     * @mbggenerated Thu Jan 09 18:27:42 CET 2014
     */
    public Integer getSeverity() {
        return severity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kom_kpia.severity
     *
     * @param severity the value for kom_kpia.severity
     *
     * @mbggenerated Thu Jan 09 18:27:42 CET 2014
     */
    public void setSeverity(Integer severity) {
        this.severity = severity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kom_kpia.value
     *
     * @return the value of kom_kpia.value
     *
     * @mbggenerated Thu Jan 09 18:27:42 CET 2014
     */
    public Double getValue() {
        return value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kom_kpia.value
     *
     * @param value the value for kom_kpia.value
     *
     * @mbggenerated Thu Jan 09 18:27:42 CET 2014
     */
    public void setValue(Double value) {
        this.value = value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kom_kpia.averageSince
     *
     * @return the value of kom_kpia.averageSince
     *
     * @mbggenerated Thu Jan 09 18:27:42 CET 2014
     */
    public Date getAverageSince() {
        return averageSince;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kom_kpia.averageSince
     *
     * @param averageSince the value for kom_kpia.averageSince
     *
     * @mbggenerated Thu Jan 09 18:27:42 CET 2014
     */
    public void setAverageSince(Date averageSince) {
        this.averageSince = averageSince;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kom_kpia.operator
     *
     * @return the value of kom_kpia.operator
     *
     * @mbggenerated Thu Jan 09 18:27:42 CET 2014
     */
    public Integer getOperator() {
        return operator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kom_kpia.operator
     *
     * @param operator the value for kom_kpia.operator
     *
     * @mbggenerated Thu Jan 09 18:27:42 CET 2014
     */
    public void setOperator(Integer operator) {
        this.operator = operator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kom_kpia.enabled
     *
     * @return the value of kom_kpia.enabled
     *
     * @mbggenerated Thu Jan 09 18:27:42 CET 2014
     */
    public Boolean getEnabled() {
        return enabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kom_kpia.enabled
     *
     * @param enabled the value for kom_kpia.enabled
     *
     * @mbggenerated Thu Jan 09 18:27:42 CET 2014
     */
    public void setEnabled(Boolean enabled) {
        this.enabled = enabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kom_kpia.description
     *
     * @return the value of kom_kpia.description
     *
     * @mbggenerated Thu Jan 09 18:27:42 CET 2014
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kom_kpia.description
     *
     * @param description the value for kom_kpia.description
     *
     * @mbggenerated Thu Jan 09 18:27:42 CET 2014
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * This method was generated.
     * This method returns the value of the database column kom_kpia.operator
     *
     * @return the value of kom_kpia.operator
     */
    public org.komea.product.database.enums.Operator getOperatorEnum() {
        return org.komea.product.database.enums.Operator.values()[operator];
    }

    /**
     * This method was generated.
     * This method sets the value of the database column kom_kpia.operator
     *
     * @param operator the value for kom_kpia.operator
     */
    public void setOperator(org.komea.product.database.enums.Operator operator) {
        this.operator = operator.ordinal();
    }

    /**
     * This method was generated.
     * This method returns the value of the database column kom_kpia.severity
     *
     * @return the value of kom_kpia.severity
     */
    public org.komea.product.database.enums.Severity getSeverityEnum() {
        return org.komea.product.database.enums.Severity.values()[severity];
    }

    /**
     * This method was generated.
     * This method sets the value of the database column kom_kpia.severity
     *
     * @param severity the value for kom_kpia.severity
     */
    public void setSeverity(org.komea.product.database.enums.Severity severity) {
        this.severity = severity.ordinal();
    }
}