package org.komea.product.database.model;

public class PersonRole {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kom_pero.idPersonRole
     *
     * @mbggenerated Wed Jan 08 17:24:48 CET 2014
     */
    private Integer idPersonRole;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kom_pero.name
     *
     * @mbggenerated Wed Jan 08 17:24:48 CET 2014
     */
    private String name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kom_pero.idPersonRole
     *
     * @return the value of kom_pero.idPersonRole
     *
     * @mbggenerated Wed Jan 08 17:24:48 CET 2014
     */
    public Integer getIdPersonRole() {
        return idPersonRole;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kom_pero.idPersonRole
     *
     * @param idPersonRole the value for kom_pero.idPersonRole
     *
     * @mbggenerated Wed Jan 08 17:24:48 CET 2014
     */
    public void setIdPersonRole(Integer idPersonRole) {
        this.idPersonRole = idPersonRole;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kom_pero.name
     *
     * @return the value of kom_pero.name
     *
     * @mbggenerated Wed Jan 08 17:24:48 CET 2014
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kom_pero.name
     *
     * @param name the value for kom_pero.name
     *
     * @mbggenerated Wed Jan 08 17:24:48 CET 2014
     */
    public void setName(String name) {
        this.name = name;
    }
}