package org.komea.product.database.model;

import java.io.Serializable;

public class Project implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kom_proj.idProject
     *
     * @mbggenerated Thu Jan 09 12:21:15 CET 2014
     */
    private Integer idProject;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kom_proj.key
     *
     * @mbggenerated Thu Jan 09 12:21:15 CET 2014
     */
    private String key;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kom_proj.name
     *
     * @mbggenerated Thu Jan 09 12:21:15 CET 2014
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kom_proj.idCustomer
     *
     * @mbggenerated Thu Jan 09 12:21:15 CET 2014
     */
    private Integer idCustomer;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kom_proj.description
     *
     * @mbggenerated Thu Jan 09 12:21:15 CET 2014
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table kom_proj
     *
     * @mbggenerated Thu Jan 09 12:21:15 CET 2014
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kom_proj
     *
     * @mbggenerated Thu Jan 09 12:21:15 CET 2014
     */
    public Project(Integer idProject, String key, String name, Integer idCustomer, String description) {
        this.idProject = idProject;
        this.key = key;
        this.name = name;
        this.idCustomer = idCustomer;
        this.description = description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kom_proj
     *
     * @mbggenerated Thu Jan 09 12:21:15 CET 2014
     */
    public Project() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kom_proj.idProject
     *
     * @return the value of kom_proj.idProject
     *
     * @mbggenerated Thu Jan 09 12:21:15 CET 2014
     */
    public Integer getIdProject() {
        return idProject;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kom_proj.idProject
     *
     * @param idProject the value for kom_proj.idProject
     *
     * @mbggenerated Thu Jan 09 12:21:15 CET 2014
     */
    public void setIdProject(Integer idProject) {
        this.idProject = idProject;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kom_proj.key
     *
     * @return the value of kom_proj.key
     *
     * @mbggenerated Thu Jan 09 12:21:15 CET 2014
     */
    public String getKey() {
        return key;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kom_proj.key
     *
     * @param key the value for kom_proj.key
     *
     * @mbggenerated Thu Jan 09 12:21:15 CET 2014
     */
    public void setKey(String key) {
        this.key = key;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kom_proj.name
     *
     * @return the value of kom_proj.name
     *
     * @mbggenerated Thu Jan 09 12:21:15 CET 2014
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kom_proj.name
     *
     * @param name the value for kom_proj.name
     *
     * @mbggenerated Thu Jan 09 12:21:15 CET 2014
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kom_proj.idCustomer
     *
     * @return the value of kom_proj.idCustomer
     *
     * @mbggenerated Thu Jan 09 12:21:15 CET 2014
     */
    public Integer getIdCustomer() {
        return idCustomer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kom_proj.idCustomer
     *
     * @param idCustomer the value for kom_proj.idCustomer
     *
     * @mbggenerated Thu Jan 09 12:21:15 CET 2014
     */
    public void setIdCustomer(Integer idCustomer) {
        this.idCustomer = idCustomer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kom_proj.description
     *
     * @return the value of kom_proj.description
     *
     * @mbggenerated Thu Jan 09 12:21:15 CET 2014
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kom_proj.description
     *
     * @param description the value for kom_proj.description
     *
     * @mbggenerated Thu Jan 09 12:21:15 CET 2014
     */
    public void setDescription(String description) {
        this.description = description;
    }
}