package org.komea.product.database.model;

public class ProviderSetting {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kom_pvds.idProviderSetting
     *
     * @mbggenerated Wed Jan 08 18:58:18 CET 2014
     */
    private Integer idProviderSetting;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kom_pvds.key
     *
     * @mbggenerated Wed Jan 08 18:58:18 CET 2014
     */
    private String key;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kom_pvds.value
     *
     * @mbggenerated Wed Jan 08 18:58:18 CET 2014
     */
    private String value;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kom_pvds.idProvider
     *
     * @mbggenerated Wed Jan 08 18:58:18 CET 2014
     */
    private Integer idProvider;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kom_pvds.idProviderSetting
     *
     * @return the value of kom_pvds.idProviderSetting
     *
     * @mbggenerated Wed Jan 08 18:58:18 CET 2014
     */
    public Integer getIdProviderSetting() {
        return idProviderSetting;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kom_pvds.idProviderSetting
     *
     * @param idProviderSetting the value for kom_pvds.idProviderSetting
     *
     * @mbggenerated Wed Jan 08 18:58:18 CET 2014
     */
    public void setIdProviderSetting(Integer idProviderSetting) {
        this.idProviderSetting = idProviderSetting;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kom_pvds.key
     *
     * @return the value of kom_pvds.key
     *
     * @mbggenerated Wed Jan 08 18:58:18 CET 2014
     */
    public String getKey() {
        return key;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kom_pvds.key
     *
     * @param key the value for kom_pvds.key
     *
     * @mbggenerated Wed Jan 08 18:58:18 CET 2014
     */
    public void setKey(String key) {
        this.key = key;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kom_pvds.value
     *
     * @return the value of kom_pvds.value
     *
     * @mbggenerated Wed Jan 08 18:58:18 CET 2014
     */
    public String getValue() {
        return value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kom_pvds.value
     *
     * @param value the value for kom_pvds.value
     *
     * @mbggenerated Wed Jan 08 18:58:18 CET 2014
     */
    public void setValue(String value) {
        this.value = value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kom_pvds.idProvider
     *
     * @return the value of kom_pvds.idProvider
     *
     * @mbggenerated Wed Jan 08 18:58:18 CET 2014
     */
    public Integer getIdProvider() {
        return idProvider;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kom_pvds.idProvider
     *
     * @param idProvider the value for kom_pvds.idProvider
     *
     * @mbggenerated Wed Jan 08 18:58:18 CET 2014
     */
    public void setIdProvider(Integer idProvider) {
        this.idProvider = idProvider;
    }
}