package org.komea.product.database.model;

import java.io.Serializable;

public class Tag implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kom_tag.idTag
     *
     * @mbggenerated Thu Jan 09 12:21:15 CET 2014
     */
    private Integer idTag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kom_tag.name
     *
     * @mbggenerated Thu Jan 09 12:21:15 CET 2014
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table kom_tag
     *
     * @mbggenerated Thu Jan 09 12:21:15 CET 2014
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kom_tag
     *
     * @mbggenerated Thu Jan 09 12:21:15 CET 2014
     */
    public Tag(Integer idTag, String name) {
        this.idTag = idTag;
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kom_tag
     *
     * @mbggenerated Thu Jan 09 12:21:15 CET 2014
     */
    public Tag() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kom_tag.idTag
     *
     * @return the value of kom_tag.idTag
     *
     * @mbggenerated Thu Jan 09 12:21:15 CET 2014
     */
    public Integer getIdTag() {
        return idTag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kom_tag.idTag
     *
     * @param idTag the value for kom_tag.idTag
     *
     * @mbggenerated Thu Jan 09 12:21:15 CET 2014
     */
    public void setIdTag(Integer idTag) {
        this.idTag = idTag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kom_tag.name
     *
     * @return the value of kom_tag.name
     *
     * @mbggenerated Thu Jan 09 12:21:15 CET 2014
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kom_tag.name
     *
     * @param name the value for kom_tag.name
     *
     * @mbggenerated Thu Jan 09 12:21:15 CET 2014
     */
    public void setName(String name) {
        this.name = name;
    }
}