/*
 * generated by Xtext
 */
package org.komea.events.dsl.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class EventDslUiModule extends org.komea.events.dsl.ui.AbstractEventDslUiModule {
	public EventDslUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
