package org.komea.product.database.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.komea.product.database.model.EventType;
import org.komea.product.database.model.EventTypeCriteria;

public interface EventTypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kom_evt
     *
     * @mbggenerated Thu Jan 09 10:55:40 CET 2014
     */
    int countByExample(EventTypeCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kom_evt
     *
     * @mbggenerated Thu Jan 09 10:55:40 CET 2014
     */
    int deleteByExample(EventTypeCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kom_evt
     *
     * @mbggenerated Thu Jan 09 10:55:40 CET 2014
     */
    int deleteByPrimaryKey(Integer idEventType);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kom_evt
     *
     * @mbggenerated Thu Jan 09 10:55:40 CET 2014
     */
    int insert(EventType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kom_evt
     *
     * @mbggenerated Thu Jan 09 10:55:40 CET 2014
     */
    int insertSelective(EventType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kom_evt
     *
     * @mbggenerated Thu Jan 09 10:55:40 CET 2014
     */
    List<EventType> selectByExampleWithBLOBs(EventTypeCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kom_evt
     *
     * @mbggenerated Thu Jan 09 10:55:40 CET 2014
     */
    List<EventType> selectByExample(EventTypeCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kom_evt
     *
     * @mbggenerated Thu Jan 09 10:55:40 CET 2014
     */
    EventType selectByPrimaryKey(Integer idEventType);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kom_evt
     *
     * @mbggenerated Thu Jan 09 10:55:40 CET 2014
     */
    int updateByExampleSelective(@Param("record") EventType record, @Param("example") EventTypeCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kom_evt
     *
     * @mbggenerated Thu Jan 09 10:55:40 CET 2014
     */
    int updateByExampleWithBLOBs(@Param("record") EventType record, @Param("example") EventTypeCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kom_evt
     *
     * @mbggenerated Thu Jan 09 10:55:40 CET 2014
     */
    int updateByExample(@Param("record") EventType record, @Param("example") EventTypeCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kom_evt
     *
     * @mbggenerated Thu Jan 09 10:55:40 CET 2014
     */
    int updateByPrimaryKeySelective(EventType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kom_evt
     *
     * @mbggenerated Thu Jan 09 10:55:40 CET 2014
     */
    int updateByPrimaryKeyWithBLOBs(EventType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kom_evt
     *
     * @mbggenerated Thu Jan 09 10:55:40 CET 2014
     */
    int updateByPrimaryKey(EventType record);
}