package org.komea.product.database.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.komea.product.database.model.GroupKind;
import org.komea.product.database.model.GroupKindExample;

public interface GroupKindMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kom_grk
     *
     * @mbggenerated Wed Jan 08 18:58:18 CET 2014
     */
    int countByExample(GroupKindExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kom_grk
     *
     * @mbggenerated Wed Jan 08 18:58:18 CET 2014
     */
    int deleteByExample(GroupKindExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kom_grk
     *
     * @mbggenerated Wed Jan 08 18:58:18 CET 2014
     */
    int deleteByPrimaryKey(Integer idGroupKind);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kom_grk
     *
     * @mbggenerated Wed Jan 08 18:58:18 CET 2014
     */
    int insert(GroupKind record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kom_grk
     *
     * @mbggenerated Wed Jan 08 18:58:18 CET 2014
     */
    int insertSelective(GroupKind record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kom_grk
     *
     * @mbggenerated Wed Jan 08 18:58:18 CET 2014
     */
    List<GroupKind> selectByExample(GroupKindExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kom_grk
     *
     * @mbggenerated Wed Jan 08 18:58:18 CET 2014
     */
    GroupKind selectByPrimaryKey(Integer idGroupKind);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kom_grk
     *
     * @mbggenerated Wed Jan 08 18:58:18 CET 2014
     */
    int updateByExampleSelective(@Param("record") GroupKind record, @Param("example") GroupKindExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kom_grk
     *
     * @mbggenerated Wed Jan 08 18:58:18 CET 2014
     */
    int updateByExample(@Param("record") GroupKind record, @Param("example") GroupKindExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kom_grk
     *
     * @mbggenerated Wed Jan 08 18:58:18 CET 2014
     */
    int updateByPrimaryKeySelective(GroupKind record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kom_grk
     *
     * @mbggenerated Wed Jan 08 18:58:18 CET 2014
     */
    int updateByPrimaryKey(GroupKind record);
}