package org.komea.product.database.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.komea.product.database.model.HasPersonEventTypeExample;
import org.komea.product.database.model.HasPersonEventTypeKey;

public interface HasPersonEventTypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kom_has_pe_evt
     *
     * @mbggenerated Wed Jan 08 17:24:48 CET 2014
     */
    int countByExample(HasPersonEventTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kom_has_pe_evt
     *
     * @mbggenerated Wed Jan 08 17:24:48 CET 2014
     */
    int deleteByExample(HasPersonEventTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kom_has_pe_evt
     *
     * @mbggenerated Wed Jan 08 17:24:48 CET 2014
     */
    int deleteByPrimaryKey(HasPersonEventTypeKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kom_has_pe_evt
     *
     * @mbggenerated Wed Jan 08 17:24:48 CET 2014
     */
    int insert(HasPersonEventTypeKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kom_has_pe_evt
     *
     * @mbggenerated Wed Jan 08 17:24:48 CET 2014
     */
    int insertSelective(HasPersonEventTypeKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kom_has_pe_evt
     *
     * @mbggenerated Wed Jan 08 17:24:48 CET 2014
     */
    List<HasPersonEventTypeKey> selectByExample(HasPersonEventTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kom_has_pe_evt
     *
     * @mbggenerated Wed Jan 08 17:24:48 CET 2014
     */
    int updateByExampleSelective(@Param("record") HasPersonEventTypeKey record, @Param("example") HasPersonEventTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kom_has_pe_evt
     *
     * @mbggenerated Wed Jan 08 17:24:48 CET 2014
     */
    int updateByExample(@Param("record") HasPersonEventTypeKey record, @Param("example") HasPersonEventTypeExample example);
}