package org.komea.product.database.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.komea.product.database.model.HasProjectPersonGroupCriteria;
import org.komea.product.database.model.HasProjectPersonGroupKey;

public interface HasProjectPersonGroupMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kom_has_proj_pegr
     *
     * @mbggenerated Mon Jan 13 16:15:52 CET 2014
     */
    int countByExample(HasProjectPersonGroupCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kom_has_proj_pegr
     *
     * @mbggenerated Mon Jan 13 16:15:52 CET 2014
     */
    int deleteByExample(HasProjectPersonGroupCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kom_has_proj_pegr
     *
     * @mbggenerated Mon Jan 13 16:15:52 CET 2014
     */
    int deleteByPrimaryKey(HasProjectPersonGroupKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kom_has_proj_pegr
     *
     * @mbggenerated Mon Jan 13 16:15:52 CET 2014
     */
    int insert(HasProjectPersonGroupKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kom_has_proj_pegr
     *
     * @mbggenerated Mon Jan 13 16:15:52 CET 2014
     */
    int insertSelective(HasProjectPersonGroupKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kom_has_proj_pegr
     *
     * @mbggenerated Mon Jan 13 16:15:52 CET 2014
     */
    List<HasProjectPersonGroupKey> selectByExample(HasProjectPersonGroupCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kom_has_proj_pegr
     *
     * @mbggenerated Mon Jan 13 16:15:52 CET 2014
     */
    int updateByExampleSelective(@Param("record") HasProjectPersonGroupKey record, @Param("example") HasProjectPersonGroupCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kom_has_proj_pegr
     *
     * @mbggenerated Mon Jan 13 16:15:52 CET 2014
     */
    int updateByExample(@Param("record") HasProjectPersonGroupKey record, @Param("example") HasProjectPersonGroupCriteria example);
}