package org.komea.product.database.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.komea.product.database.model.KpiAlertType;
import org.komea.product.database.model.KpiAlertTypeCriteria;

public interface KpiAlertTypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kom_kpia
     *
     * @mbggenerated Thu Jan 09 19:15:19 CET 2014
     */
    int countByExample(KpiAlertTypeCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kom_kpia
     *
     * @mbggenerated Thu Jan 09 19:15:19 CET 2014
     */
    int deleteByExample(KpiAlertTypeCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kom_kpia
     *
     * @mbggenerated Thu Jan 09 19:15:19 CET 2014
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kom_kpia
     *
     * @mbggenerated Thu Jan 09 19:15:19 CET 2014
     */
    int insert(KpiAlertType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kom_kpia
     *
     * @mbggenerated Thu Jan 09 19:15:19 CET 2014
     */
    int insertSelective(KpiAlertType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kom_kpia
     *
     * @mbggenerated Thu Jan 09 19:15:19 CET 2014
     */
    List<KpiAlertType> selectByExampleWithBLOBs(KpiAlertTypeCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kom_kpia
     *
     * @mbggenerated Thu Jan 09 19:15:19 CET 2014
     */
    List<KpiAlertType> selectByExample(KpiAlertTypeCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kom_kpia
     *
     * @mbggenerated Thu Jan 09 19:15:19 CET 2014
     */
    KpiAlertType selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kom_kpia
     *
     * @mbggenerated Thu Jan 09 19:15:19 CET 2014
     */
    int updateByExampleSelective(@Param("record") KpiAlertType record, @Param("example") KpiAlertTypeCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kom_kpia
     *
     * @mbggenerated Thu Jan 09 19:15:19 CET 2014
     */
    int updateByExampleWithBLOBs(@Param("record") KpiAlertType record, @Param("example") KpiAlertTypeCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kom_kpia
     *
     * @mbggenerated Thu Jan 09 19:15:19 CET 2014
     */
    int updateByExample(@Param("record") KpiAlertType record, @Param("example") KpiAlertTypeCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kom_kpia
     *
     * @mbggenerated Thu Jan 09 19:15:19 CET 2014
     */
    int updateByPrimaryKeySelective(KpiAlertType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kom_kpia
     *
     * @mbggenerated Thu Jan 09 19:15:19 CET 2014
     */
    int updateByPrimaryKeyWithBLOBs(KpiAlertType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kom_kpia
     *
     * @mbggenerated Thu Jan 09 19:15:19 CET 2014
     */
    int updateByPrimaryKey(KpiAlertType record);
}