package org.komea.product.database.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.komea.product.database.model.PersonGroup;
import org.komea.product.database.model.PersonGroupCriteria;

public interface PersonGroupMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kom_pegr
     *
     * @mbggenerated Thu Jan 16 12:45:33 CET 2014
     */
    int countByExample(PersonGroupCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kom_pegr
     *
     * @mbggenerated Thu Jan 16 12:45:33 CET 2014
     */
    int deleteByExample(PersonGroupCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kom_pegr
     *
     * @mbggenerated Thu Jan 16 12:45:33 CET 2014
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kom_pegr
     *
     * @mbggenerated Thu Jan 16 12:45:33 CET 2014
     */
    int insert(PersonGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kom_pegr
     *
     * @mbggenerated Thu Jan 16 12:45:33 CET 2014
     */
    int insertSelective(PersonGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kom_pegr
     *
     * @mbggenerated Thu Jan 16 12:45:33 CET 2014
     */
    List<PersonGroup> selectByExample(PersonGroupCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kom_pegr
     *
     * @mbggenerated Thu Jan 16 12:45:33 CET 2014
     */
    PersonGroup selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kom_pegr
     *
     * @mbggenerated Thu Jan 16 12:45:33 CET 2014
     */
    int updateByExampleSelective(@Param("record") PersonGroup record, @Param("example") PersonGroupCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kom_pegr
     *
     * @mbggenerated Thu Jan 16 12:45:33 CET 2014
     */
    int updateByExample(@Param("record") PersonGroup record, @Param("example") PersonGroupCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kom_pegr
     *
     * @mbggenerated Thu Jan 16 12:45:33 CET 2014
     */
    int updateByPrimaryKeySelective(PersonGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kom_pegr
     *
     * @mbggenerated Thu Jan 16 12:45:33 CET 2014
     */
    int updateByPrimaryKey(PersonGroup record);
}