package org.komea.product.database.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.komea.product.database.model.Project;
import org.komea.product.database.model.ProjectCriteria;

public interface ProjectMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kom_proj
     *
     * @mbggenerated Thu Jan 09 12:21:15 CET 2014
     */
    int countByExample(ProjectCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kom_proj
     *
     * @mbggenerated Thu Jan 09 12:21:15 CET 2014
     */
    int deleteByExample(ProjectCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kom_proj
     *
     * @mbggenerated Thu Jan 09 12:21:15 CET 2014
     */
    int deleteByPrimaryKey(Integer idProject);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kom_proj
     *
     * @mbggenerated Thu Jan 09 12:21:15 CET 2014
     */
    int insert(Project record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kom_proj
     *
     * @mbggenerated Thu Jan 09 12:21:15 CET 2014
     */
    int insertSelective(Project record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kom_proj
     *
     * @mbggenerated Thu Jan 09 12:21:15 CET 2014
     */
    List<Project> selectByExampleWithBLOBs(ProjectCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kom_proj
     *
     * @mbggenerated Thu Jan 09 12:21:15 CET 2014
     */
    List<Project> selectByExample(ProjectCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kom_proj
     *
     * @mbggenerated Thu Jan 09 12:21:15 CET 2014
     */
    Project selectByPrimaryKey(Integer idProject);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kom_proj
     *
     * @mbggenerated Thu Jan 09 12:21:15 CET 2014
     */
    int updateByExampleSelective(@Param("record") Project record, @Param("example") ProjectCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kom_proj
     *
     * @mbggenerated Thu Jan 09 12:21:15 CET 2014
     */
    int updateByExampleWithBLOBs(@Param("record") Project record, @Param("example") ProjectCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kom_proj
     *
     * @mbggenerated Thu Jan 09 12:21:15 CET 2014
     */
    int updateByExample(@Param("record") Project record, @Param("example") ProjectCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kom_proj
     *
     * @mbggenerated Thu Jan 09 12:21:15 CET 2014
     */
    int updateByPrimaryKeySelective(Project record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kom_proj
     *
     * @mbggenerated Thu Jan 09 12:21:15 CET 2014
     */
    int updateByPrimaryKeyWithBLOBs(Project record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kom_proj
     *
     * @mbggenerated Thu Jan 09 12:21:15 CET 2014
     */
    int updateByPrimaryKey(Project record);
}