package org.komea.product.database.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.komea.product.database.model.ProviderSetting;
import org.komea.product.database.model.ProviderSettingExample;

public interface ProviderSettingMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kom_pvds
     *
     * @mbggenerated Wed Jan 08 17:24:48 CET 2014
     */
    int countByExample(ProviderSettingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kom_pvds
     *
     * @mbggenerated Wed Jan 08 17:24:48 CET 2014
     */
    int deleteByExample(ProviderSettingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kom_pvds
     *
     * @mbggenerated Wed Jan 08 17:24:48 CET 2014
     */
    int deleteByPrimaryKey(Integer idProviderSetting);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kom_pvds
     *
     * @mbggenerated Wed Jan 08 17:24:48 CET 2014
     */
    int insert(ProviderSetting record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kom_pvds
     *
     * @mbggenerated Wed Jan 08 17:24:48 CET 2014
     */
    int insertSelective(ProviderSetting record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kom_pvds
     *
     * @mbggenerated Wed Jan 08 17:24:48 CET 2014
     */
    List<ProviderSetting> selectByExample(ProviderSettingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kom_pvds
     *
     * @mbggenerated Wed Jan 08 17:24:48 CET 2014
     */
    ProviderSetting selectByPrimaryKey(Integer idProviderSetting);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kom_pvds
     *
     * @mbggenerated Wed Jan 08 17:24:48 CET 2014
     */
    int updateByExampleSelective(@Param("record") ProviderSetting record, @Param("example") ProviderSettingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kom_pvds
     *
     * @mbggenerated Wed Jan 08 17:24:48 CET 2014
     */
    int updateByExample(@Param("record") ProviderSetting record, @Param("example") ProviderSettingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kom_pvds
     *
     * @mbggenerated Wed Jan 08 17:24:48 CET 2014
     */
    int updateByPrimaryKeySelective(ProviderSetting record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kom_pvds
     *
     * @mbggenerated Wed Jan 08 17:24:48 CET 2014
     */
    int updateByPrimaryKey(ProviderSetting record);
}